package com.wtshop.model;

import com.wtshop.entity.ProductImage;
import com.wtshop.model.base.BaseActivity;
import com.wtshop.util.ObjectUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Activity extends BaseActivity<Activity> {
	public static final Activity dao = new Activity().dao();
	/**
	 * 商品图片
	 */
	private List<ActivityProduct> activityProduct = new ArrayList<ActivityProduct>();

	public List<ActivityProduct> getActivityProduct() {

		if (ObjectUtils.isEmpty(activityProduct)) {

			String sql = "select * from activity_product a where a.activity_id="+getId()+" and  a.maxNum>a.ptNum";

			 activityProduct=ActivityProduct.dao.find(sql);
		}


		return activityProduct;
	}

	public void setActivityProduct(List<ActivityProduct> activityProduct) {
		this.activityProduct = activityProduct;
	}
}
