package com.wtshop.model;

import com.wtshop.model.base.BaseActIntroduce;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActIntroduce extends BaseActIntroduce<ActIntroduce> {
	public static final ActIntroduce dao = new ActIntroduce().dao();
}
