package com.wtshop.model;

import com.wtshop.model.base.BaseActivityStore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActivityStore extends BaseActivityStore<ActivityStore> {
	public static final ActivityStore dao = new ActivityStore().dao();
}
