package com.wtshop.model;

import com.wtshop.model.base.BaseActivityProduct;
import com.wtshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActivityProduct extends BaseActivityProduct<ActivityProduct> {
	public static final ActivityProduct dao = new ActivityProduct().dao();


	private Product product;

	public Product getProduct() {
		if(ObjectUtils.isEmpty(product)){
			product = Product.dao.findById(getProductId());
		}
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}


}
