package com.wtshop.model;

import com.wtshop.model.base.BaseActivity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Activity extends BaseActivity<Activity> {
	public static final Activity dao = new Activity().dao();
}
