package com.wtshop.model;

import com.wtshop.model.base.BaseAppManage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppManage extends BaseAppManage<AppManage> {
	public static final AppManage dao = new AppManage().dao();
}
