package com.wtshop.model;

import com.wtshop.model.base.BaseAppVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppVersion extends BaseAppVersion<AppVersion> {
	public static final AppVersion dao = new AppVersion().dao();
}
