package com.wtshop.model;

import com.wtshop.model.base.BaseAreaDescribe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AreaDescribe extends BaseAreaDescribe<AreaDescribe> {
	public static final AreaDescribe dao = new AreaDescribe().dao();
}
