package com.wtshop.model;

import com.wtshop.model.base.BaseBargainHistroy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BargainHistroy extends BaseBargainHistroy<BargainHistroy> {
	public static final BargainHistroy dao = new BargainHistroy().dao();
}
