package com.wtshop.model;

import com.wtshop.model.base.BaseBargainPersonal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BargainPersonal extends BaseBargainPersonal<BargainPersonal> {
	public static final BargainPersonal dao = new BargainPersonal().dao();
}
