package com.wtshop.model;

import com.wtshop.model.base.BaseBargainHelp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BargainHelp extends BaseBargainHelp<BargainHelp> {
	public static final BargainHelp dao = new BargainHelp().dao();
}
