package com.wtshop.model;

import com.wtshop.model.base.BaseBargainDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BargainDetail extends BaseBargainDetail<BargainDetail> {
	public static final BargainDetail dao = new BargainDetail().dao();
}
