package com.wtshop.model;

import com.wtshop.model.base.BaseBargain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bargain extends BaseBargain<Bargain> {
	public static final Bargain dao = new Bargain().dao();
}
