package com.wtshop.model;

import com.wtshop.model.base.BaseButlerUpgradeLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ButlerUpgradeLog extends BaseButlerUpgradeLog<ButlerUpgradeLog> {
	public static final ButlerUpgradeLog dao = new ButlerUpgradeLog().dao();
}
