package com.wtshop.model;

import com.wtshop.model.base.BaseCartMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CartMember extends BaseCartMember<CartMember> {
	public static final CartMember dao = new CartMember().dao();
}
