package com.wtshop.model;

import com.wtshop.model.base.BaseCertificates;
import com.wtshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Certificates extends BaseCertificates<Certificates> {
	public static final Certificates dao = new Certificates().dao();
	private Member member;

	public Member getMember() {
		if(ObjectUtils.isEmpty(member)){
			member = Member.dao.findById(getMemberId());
		}
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}
}
