package com.wtshop.model;

import com.wtshop.model.base.BaseCharacterCommend;
import com.wtshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CharacterCommend extends BaseCharacterCommend<CharacterCommend> {

	public static final CharacterCommend dao = new CharacterCommend().dao();

	private Goods goods;

	/**
	 * 获取货品
	 *
	 * @return 货品
	 */
	public Goods getGoods() {
		if (ObjectUtils.isEmpty(goods)) {
			goods = Goods.dao.findById(getGoodsId());
		}
		return goods;
	}

	/**
	 * 设置货品
	 *
	 * @param goods
	 *            货品
	 */
	public void setGoods(Goods goods) {
		this.goods = goods;
	}

}
