package com.wtshop.model;

import com.wtshop.model.base.BaseCommissionLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommissionLog extends BaseCommissionLog<CommissionLog> {
	public static final CommissionLog dao = new CommissionLog().dao();
}
