package com.wtshop.model;

import com.wtshop.model.base.BaseCommExchangeProgress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommExchangeProgress extends BaseCommExchangeProgress<CommExchangeProgress> {
	public static final CommExchangeProgress dao = new CommExchangeProgress().dao();
}
