package com.wtshop.model;

import com.wtshop.model.base.BaseCommissionHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommissionHistory extends BaseCommissionHistory<CommissionHistory> {
	public static final CommissionHistory dao = new CommissionHistory().dao();
}
