package com.wtshop.model;

import com.wtshop.model.base.BaseCouponShare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CouponShare extends BaseCouponShare<CouponShare> {
	public static final CouponShare dao = new CouponShare().dao();
}
