package com.wtshop.model;

import com.wtshop.model.base.BaseEffect;
import org.apache.commons.collections.CollectionUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Effect extends BaseEffect<Effect> {
	public static final Effect dao = new Effect().dao();

	/** 货品 */
	private List<Goods> goods = new ArrayList<Goods>();
	/**
	 * 获取货品
	 *
	 * @return 货品
	 */
	public List<Goods> getGoods() {
		if (CollectionUtils.isEmpty(goods)) {
			String sql = "SELECT g.* FROM `goods_effct` gt LEFT JOIN `goods` g ON gt.`goods` = g.`id` WHERE gt.`effect` = ?";
			goods = Goods.dao.find(sql, getId());
		}
		return goods;
	}

	/**
	 * 设置货品
	 *
	 * @param goods
	 *            货品
	 */
	public void setGoods(List<Goods> goods) {
		this.goods = goods;
	}


}
