package com.wtshop.model;

import com.wtshop.model.base.BaseExchangeProgress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExchangeProgress extends BaseExchangeProgress<ExchangeProgress> {
	public static final ExchangeProgress dao = new ExchangeProgress().dao();
}
