package com.wtshop.model;

import com.wtshop.model.base.BaseExchangeLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExchangeLog extends BaseExchangeLog<ExchangeLog> {
	public static final ExchangeLog dao = new ExchangeLog().dao();
}
