package com.wtshop.model;

import com.alibaba.fastjson.JSONArray;
import com.wtshop.model.base.BaseFeedback;
import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang3.StringUtils;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Feedback extends BaseFeedback<Feedback> {
	public static final Feedback dao = new Feedback().dao();

	/**
	 * 获取图片
	 *
	 * @return 图片
	 */
	public List<String> getImagesConverter() {
		List<String> images = new ArrayList<String>();
		String images1 = getImage();
		if(StringUtils.isNotEmpty(images1)){
			String[] split = images1.split(",");
			images = Arrays.asList(split);
		}
		return images;
	}

}
