package com.wtshop.model;

import com.wtshop.model.base.BaseFightGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FightGroup extends BaseFightGroup<FightGroup> {
	public static final FightGroup dao = new FightGroup().dao();
}
