package com.wtshop.model;

import com.wtshop.model.base.BaseFlashsale;
import com.wtshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Flashsale extends BaseFlashsale<Flashsale> {


	public static final Flashsale dao = new Flashsale().dao();

	/**
	 * 类型
	 */
	public enum Type {

		/** 已完成 */
		complete,

		/** 当前准备开始 已就绪*/
		ready,

		/** 下一期筹备 未就绪*/
		nextReady,

		/** 普通 */
		normal,

	}



	private ProductCategory productCategory;

	public ProductCategory getProductCategory() {
		if(ObjectUtils.isEmpty(productCategory)){
			productCategory = ProductCategory.dao.findById(getProductCategoryId());
		}
		return productCategory;
	}

	public void setProductCategory(ProductCategory productCategory) {
		this.productCategory = productCategory;
	}
}
