package com.wtshop.model;

import com.wtshop.model.base.BaseFlashsaleDetail;
import com.wtshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FlashsaleDetail extends BaseFlashsaleDetail<FlashsaleDetail> {
	public static final FlashsaleDetail dao = new FlashsaleDetail().dao();
	private Product product;

	public Product getProduct() {
		if(ObjectUtils.isEmpty(product)){
			product = Product.dao.findById(getProductId());
		}
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}
}
