package com.wtshop.model;

import com.wtshop.model.base.BaseFootprint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Footprint extends BaseFootprint<Footprint> {
	public static final Footprint dao = new Footprint().dao();
}
