package com.wtshop.model;

import com.wtshop.model.base.BaseFreeApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FreeApply extends BaseFreeApply<FreeApply> {
	public static final FreeApply dao = new FreeApply().dao();
}
