package com.wtshop.model;

import com.wtshop.model.base.BaseFudaiProduct;
import com.wtshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FudaiProduct extends BaseFudaiProduct<FudaiProduct> {
	public FudaiProduct(){};
	public FudaiProduct(Long productId,Long fudaiId,int ismain){
		this.setIsMain(ismain);
		this.setProductId(productId);
		this.setFudaiId(fudaiId);
	}
	public static final FudaiProduct dao = new FudaiProduct().dao();
	private Product product;

	public Product getProduct() {
		if(ObjectUtils.isEmpty(product)){
			product = Product.dao.findById(getProductId());
		}
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}
}
