package com.wtshop.model;

import com.wtshop.model.base.BaseFudaiImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FudaiImg extends BaseFudaiImg<FudaiImg> {
	public static final FudaiImg dao = new FudaiImg().dao();
}
