package com.wtshop.model;

import com.wtshop.model.base.BaseFullAnti;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FullAnti extends BaseFullAnti<FullAnti> {
	public static final FullAnti dao = new FullAnti().dao();
}
