package com.wtshop.model;

import com.wtshop.model.base.BaseFullReduction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FullReduction extends BaseFullReduction<FullReduction> {
	public static final FullReduction dao = new FullReduction().dao();
}
