package com.wtshop.model;

import com.wtshop.model.base.BaseFunction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Function extends BaseFunction<Function> {
	public static final Function dao = new Function().dao();
}
