package com.wtshop.model;

import com.jfinal.plugin.activerecord.Db;
import com.wtshop.model.base.BaseGoodsEffct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsEffct extends BaseGoodsEffct<GoodsEffct> {
	public static final GoodsEffct dao = new GoodsEffct().dao();

	public boolean delete(Long goods) {
		return Db.deleteById("goods_effct", "goods", goods);
	}
}
