package com.wtshop.model;

import com.wtshop.model.base.BaseGoodsReview;
import org.apache.commons.collections.CollectionUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsReview extends BaseGoodsReview<GoodsReview> {
    public static final GoodsReview dao = new GoodsReview().dao();

    private Goods goods = null;
    private Admin admin = null;

    public Goods getGoods() {
        if (goods == null) {
            goods = Goods.dao.findFirst("select * from goods where id = " + getGoodsId());
        }
        return goods;
    }

    public Admin getAdmin(){
        if (admin == null){
            admin = Admin.dao.findFirst("select * from admin where id = " + getAdminId());
        }
        return admin;
    }
}
