package com.wtshop.model;

import com.wtshop.model.base.BaseGoodsOperFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsOperFlow extends BaseGoodsOperFlow<GoodsOperFlow> {
	public static final GoodsOperFlow dao = new GoodsOperFlow().dao();
}
