package com.wtshop.model;

import com.wtshop.model.base.BaseGroupBuy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupBuy extends BaseGroupBuy<GroupBuy> {
	public static final GroupBuy dao = new GroupBuy().dao();
}
