package com.wtshop.model;

import com.wtshop.model.base.BaseGroupsJoin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupsJoin extends BaseGroupsJoin<GroupsJoin> {
	public static final GroupsJoin dao = new GroupsJoin().dao();
}
