package com.wtshop.model;

import com.wtshop.model.base.BaseGroupsCreate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupsCreate extends BaseGroupsCreate<GroupsCreate> {
	public static final GroupsCreate dao = new GroupsCreate().dao();
}
