package com.wtshop.model;

import com.wtshop.model.base.BaseGroupBuy;
import com.wtshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupBuy extends BaseGroupBuy<GroupBuy> {
	public static final GroupBuy dao = new GroupBuy().dao();
	//  福袋状态    0/已发布,1/未发布
	public final static boolean State_Active = true;
	public final static boolean State_UnActive = false;

	private Product product;

	public Product getProduct() {
		if(ObjectUtils.isEmpty(product)){
			product = Product.dao.findById(getProductId());
		}
		return product;
	}

	public void setProduct(Product product) {

		if(ObjectUtils.isEmpty(product)){
			product = Product.dao.findById(getProductId());
		}
		this.product = product;
	}

}
