package com.wtshop.model;

import com.wtshop.model.base.BaseGroups;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Groups extends BaseGroups<Groups> {
	public static final Groups dao = new Groups().dao();
}
