package com.wtshop.model;

import com.wtshop.model.base.BaseGroupRemind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupRemind extends BaseGroupRemind<GroupRemind> {
	public static final GroupRemind dao = new GroupRemind().dao();

}
