package com.wtshop.model;

import com.wtshop.model.base.BaseHouserkeeperGrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HouserkeeperGrade extends BaseHouserkeeperGrade<HouserkeeperGrade> {
	public static final HouserkeeperGrade dao = new HouserkeeperGrade().dao();
}
