package com.wtshop.model;

import com.wtshop.model.base.BaseIdentifier;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Identifier extends BaseIdentifier<Identifier> {
	public static final Identifier dao = new Identifier().dao();
}
