package com.wtshop.model;

import com.wtshop.model.base.BaseIdentifier;
import com.wtshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Identifier extends BaseIdentifier<Identifier> {
	public static final Identifier dao = new Identifier().dao();
	public Member member;
	/**
	 * 获取会员
	 *
	 * @return 会员
	 */
	public Member getMember() {
		if (ObjectUtils.isEmpty(member)) {
			System.out.println("打印222222222222222222222222"+"select * from member m where m.share_code='"+getShareCode()+"'");

			member = Member.dao.findFirst("select * from member m where m.share_code='"+getShareCode()+"'");
			System.out.println(member.toString());
		}
		return member;
	}

	/**
	 * 设置会员
	 *
	 * @param member
	 *            会员
	 */
	public void setMember(Member member) {
		this.member = member;
	}

}
