package com.wtshop.model;

import com.wtshop.model.base.BaseIdentifierLog;
import com.wtshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IdentifierLog extends BaseIdentifierLog<IdentifierLog> {
	public static final IdentifierLog dao = new IdentifierLog().dao();
	/**
	 * 类型
	 */
	public enum Type {

		/** 订单创建 */
		create,

		/** 订单更新 */
		update,

		/** 订单取消 */
		cancel,

		/** 订单审核 */
		review,

		/** 订单收款 */
		payment,

		/** 订单退款 */
		refunds,

		/** 订单发货 */
		shipping,

		/** 订单退货 */
		returns,

		/** 订单收货 */
		receive,

		/** 订单完成 */
		complete,

		/** 订单失败 */
		fail
	}

	/** 订单 */
	private Identifier identifier;

	/**
	 * 类型
	 */
	public OrderLog.Type getTypeName() {
		return OrderLog.Type.values()[getType()];
	}

	/**
	 * 构造方法
	 */
	public IdentifierLog() {
	}

	/**
	 * 构造方法
	 *
	 * @param type
	 *            类型
	 * @param operator
	 *            操作员
	 */
	public IdentifierLog(OrderLog.Type type, String operator) {
		this.setType(type.ordinal());
		this.setOperator(operator);
	}

	/**
	 * 构造方法
	 *
	 * @param type
	 *            类型
	 * @param operator
	 *            操作员
	 * @param content
	 *            内容
	 */
	public IdentifierLog(OrderLog.Type type, String operator, String content) {
		this.setType(type.ordinal());
		this.setOperator(operator);
		this.setContent(content);
	}

	/**
	 * 获取订单
	 *
	 * @return 订单
	 */
	public Identifier getIdentifier() {
		if (ObjectUtils.isEmpty(identifier)) {
			identifier = Identifier.dao.findById(getIdentifierId());
		}
		return identifier;
	}

	/**
	 * 设置订单
	 *
	 * @param identifier
	 *            订单
	 */
	public void setIdentifier(Identifier identifier) {
		this.identifier = identifier;
	}

	/**
	 * 设置操作员
	 *
	 * @param operator
	 *            操作员
	 */
	public void setOperator(Admin operator) {
		setOperator(operator != null ? operator.getUsername() : null);
	}
}
