package com.wtshop.model;

import com.wtshop.model.base.BaseIdentifierLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IdentifierLog extends BaseIdentifierLog<IdentifierLog> {
	public static final IdentifierLog dao = new IdentifierLog().dao();
}
