package com.wtshop.model;

import com.wtshop.model.base.BaseIntegralLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralLog extends BaseIntegralLog<IntegralLog> {
	public static final IntegralLog dao = new IntegralLog().dao();
}
