package com.wtshop.model;

import com.wtshop.model.base.BaseIntegralStore;
import com.wtshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralStore extends BaseIntegralStore<IntegralStore> {





	public static final IntegralStore dao = new IntegralStore().dao();
	public Member memberStore;

	public Member getMemberStore() {
		if (ObjectUtils.isEmpty(memberStore)) {
			memberStore = Member.dao.findById(getStoreMemberId());
		}

		return memberStore;

	}

	public void setMemberStore(Member memberStore) {
		this.memberStore = memberStore;
	}


}
