package com.wtshop.model;

import com.wtshop.model.base.BaseIntegralStoreLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralStoreLog extends BaseIntegralStoreLog<IntegralStoreLog> {
	public static final IntegralStoreLog dao = new IntegralStoreLog().dao();
}
