package com.wtshop.model;

import com.wtshop.model.base.BaseInterestCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InterestCategory extends BaseInterestCategory<InterestCategory> {
	public static final InterestCategory dao = new InterestCategory().dao();
}
