package com.wtshop.model;

import com.wtshop.model.base.BaseIntegralStore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralStore extends BaseIntegralStore<IntegralStore> {
	public static final IntegralStore dao = new IntegralStore().dao();
}
