package com.wtshop.model;

import com.wtshop.model.base.BaseIntegralStoreLog;
import com.wtshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntegralStoreLog extends BaseIntegralStoreLog<IntegralStoreLog> {
	public static final IntegralStoreLog dao = new IntegralStoreLog().dao();

	public Member memberStore;

	public Member getMemberStore() {
		if (ObjectUtils.isEmpty(memberStore)) {
			memberStore = Member.dao.findById(getStoreMemberId());
		}

		return memberStore;

	}

	public void setMemberStore(Member memberStore) {
		this.memberStore = memberStore;
	}

}
