package com.wtshop.model;

import com.wtshop.model.base.BaseLikeCommend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LikeCommend extends BaseLikeCommend<LikeCommend> {
	public static final LikeCommend dao = new LikeCommend().dao();
}
