package com.wtshop.model;

import com.wtshop.model.base.BaseMemberFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberFeedback extends BaseMemberFeedback<MemberFeedback> {
	public static final MemberFeedback dao = new MemberFeedback().dao();
}
