package com.wtshop.model;

import com.wtshop.model.base.BaseMemberInterestCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberInterestCategory extends BaseMemberInterestCategory<MemberInterestCategory> {
	public static final MemberInterestCategory dao = new MemberInterestCategory().dao();
}
