package com.wtshop.model;

import com.wtshop.model.base.BaseMemberSkinType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberSkinType extends BaseMemberSkinType<MemberSkinType> {
	public static final MemberSkinType dao = new MemberSkinType().dao();
}
