package com.wtshop.model;

import com.wtshop.model.base.BaseMessageLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MessageLink extends BaseMessageLink<MessageLink> {
	public static final MessageLink dao = new MessageLink().dao();
}
