package com.wtshop.model;

import com.wtshop.model.base.BaseMiaobiLssuelog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MiaobiLssuelog extends BaseMiaobiLssuelog<MiaobiLssuelog> {
	public static final MiaobiLssuelog dao = new MiaobiLssuelog().dao();
}
