package com.wtshop.model;

import com.wtshop.model.base.BaseMiaobiLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MiaobiLog extends BaseMiaobiLog<MiaobiLog> {
	public static final MiaobiLog dao = new MiaobiLog().dao();
}
