package com.wtshop.model;

import com.wtshop.model.base.BaseMiaobiLssue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MiaobiLssue extends BaseMiaobiLssue<MiaobiLssue> {
	public static final MiaobiLssue dao = new MiaobiLssue().dao();
}
