package com.wtshop.model;

import com.wtshop.model.base.BaseMrmfShop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MrmfShop extends BaseMrmfShop<MrmfShop> {
	public static final MrmfShop dao = new MrmfShop().dao();
}
