package com.wtshop.model;

import com.wtshop.model.base.BaseNewgoodsCommend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewgoodsCommend extends BaseNewgoodsCommend<NewgoodsCommend> {
	public static final NewgoodsCommend dao = new NewgoodsCommend().dao();
}
