package com.wtshop.model;

import com.wtshop.model.base.BaseNodifyGoodsSend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NodifyGoodsSend extends BaseNodifyGoodsSend<NodifyGoodsSend> {
	public static final NodifyGoodsSend dao = new NodifyGoodsSend().dao();
}
