package com.wtshop.model;

import com.wtshop.model.base.BaseOrderCancel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderCancel extends BaseOrderCancel<OrderCancel> {
	public static final OrderCancel dao = new OrderCancel().dao();
}
