package com.wtshop.model;

import com.wtshop.model.base.BasePartner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Partner extends BasePartner<Partner> {
	public static final Partner dao = new Partner().dao();
}
