package com.wtshop.model;

import com.wtshop.model.base.BasePrestore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Prestore extends BasePrestore<Prestore> {
	public static final Prestore dao = new Prestore().dao();
}
