package com.wtshop.model;

import com.wtshop.model.base.BaseRaffle;
import org.apache.xmlbeans.impl.xb.xsdschema.Public;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Raffle extends BaseRaffle<Raffle> {
	public static final Raffle dao = new Raffle().dao();
	private Activity activity;
	private Member member ;
	private ActivityProduct activityProduct ;
	public Member getMember() {
		member=Member.dao.findById(getMemberId());
		return member;
	}

	public ActivityProduct getActivityProduct() {
		activityProduct=ActivityProduct.dao.findById(getActivityProductId());
		return activityProduct;
	}

	public void setActivityProduct(ActivityProduct activityProduct) {
		this.activityProduct = activityProduct;
	}

	public Activity getActivity() {

		activity=Activity.dao.findById(getActivityId());
		return activity;
	}
	/**
	 *   是否是实物
	 */
	public enum IsReal {

		/** 不是 */
		no,

		/** 是 */
		yes
	}

	public void setMember(Member member) {
		this.member = member;
	}




	public void setActivity(Activity activity) {
		this.activity = activity;
	}
}
