package com.wtshop.model;

import com.wtshop.model.base.BaseRaffle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Raffle extends BaseRaffle<Raffle> {
	public static final Raffle dao = new Raffle().dao();
}
