package com.wtshop.model;

import com.wtshop.model.base.BaseReferrerConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReferrerConfig extends BaseReferrerConfig<ReferrerConfig> {

	public static final ReferrerConfig dao = new ReferrerConfig().dao();

	public final static String kRecommendStaff = "RECOMMEND_STAFF:";
	public final static String kReferrerConfig_Referrer_Time = "REFERRER_TIME:";
	public final static String kReferrerConfig_Referrer_Num = "REFERRER_NUM:";

}
