package com.wtshop.model;

import com.wtshop.model.base.BaseReferrerGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReferrerGoods extends BaseReferrerGoods<ReferrerGoods> {
	public static final ReferrerGoods dao = new ReferrerGoods().dao();
	public ReferrerGoods (){}
	public ReferrerGoods (Long staffId,Long memberId,Long goodsId,int status){
		this.setStaffId(staffId);
		this.setMemberId(memberId);
		this.setGoodsId(goodsId);
		this.setStatus(status);
	}
}
