package com.wtshop.model;

import com.wtshop.model.base.BaseReturnsItemProgress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReturnsItemProgress extends BaseReturnsItemProgress<ReturnsItemProgress> {
	public static final ReturnsItemProgress dao = new ReturnsItemProgress().dao();
}
