package com.wtshop.model;


import com.wtshop.model.base.BaseReverseAuction;
import org.apache.commons.collections.CollectionUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReverseAuction extends BaseReverseAuction<ReverseAuction> {

    //  0/停止, 1/草稿, 2/待审核, 4/待产品主管审核, 6/待财务审核, 7/待财务主管审核, 8/上线, 10/已完成
    public final static int State_Stop = 0;
    public final static int State_Draft = 1;
    public final static int State_Review_ProductSpecialist = 2;
    public final static int State_Review_ProductManager = 4;
    public final static int State_Review_Financial = 6;
    public final static int State_Review_FinanceDirector = 7;
    public final static int State_Publish = 8;
    public final static int State_Current = 9;
    public final static int State_Finished = 10;

    public static final ReverseAuction dao = new ReverseAuction().dao();

    private List<ReverseAuctionDetail> reverseAuctionDetails = new ArrayList<ReverseAuctionDetail>();

    public List<ReverseAuctionDetail> getReverseAuctionDetails() {
        if (CollectionUtils.isEmpty(reverseAuctionDetails)) {
            String sql = "select * from reverse_auction_detail where reverse_auction_id = " + getId();
            reverseAuctionDetails = ReverseAuctionDetail.dao.find(sql);
        }
        return reverseAuctionDetails;
    }

    public void setReverseAuctionDetails(List<ReverseAuctionDetail> reverseauctionDetails) {
        this.reverseAuctionDetails = reverseauctionDetails;
    }

    public boolean isOnline() {
        return (this.getState().intValue() == State_Stop || this.getState().intValue() >= State_Publish);
    }

}
