package com.wtshop.model;

import com.wtshop.model.base.BaseReverseAuctionDetail;
import com.wtshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReverseAuctionDetail extends BaseReverseAuctionDetail<ReverseAuctionDetail> {
    public static final ReverseAuctionDetail dao = new ReverseAuctionDetail().dao();
    private Product product;

    public Product getProduct() {
        if (ObjectUtils.isEmpty(product)) {
            product = Product.dao.findById(getProductId());
        }
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }
}
