package com.wtshop.model;

import com.wtshop.model.base.BaseReverseAuctionHistroy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReverseAuctionHistroy extends BaseReverseAuctionHistroy<ReverseAuctionHistroy> {
	public static final ReverseAuctionHistroy dao = new ReverseAuctionHistroy().dao();
}
