package com.wtshop.model;

import com.wtshop.model.base.BaseReverseAuctionOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReverseAuctionOrder extends BaseReverseAuctionOrder<ReverseAuctionOrder> {
	public static final ReverseAuctionOrder dao = new ReverseAuctionOrder().dao();
}
