package com.wtshop.model;


import com.wtshop.model.base.BaseReverseAuctionReminds;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReverseAuctionReminds extends BaseReverseAuctionReminds<ReverseAuctionReminds> {
	public static final ReverseAuctionReminds dao = new ReverseAuctionReminds().dao();
}
