package com.wtshop.model;

import com.wtshop.model.base.BaseSkinType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SkinType extends BaseSkinType<SkinType> {
	public static final SkinType dao = new SkinType().dao();
}
