package com.wtshop.model;

import com.wtshop.model.base.BaseSpecialPersonnel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecialPersonnel extends BaseSpecialPersonnel<SpecialPersonnel> {
	public static final SpecialPersonnel dao = new SpecialPersonnel().dao();
}
