package com.wtshop.model;

import com.wtshop.model.base.BaseSpecialGoods;
import com.wtshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecialGoods extends BaseSpecialGoods<SpecialGoods> {
	public static final SpecialGoods dao = new SpecialGoods().dao();
	private Goods goods;

	public Goods getGoods() {
		if(ObjectUtils.isEmpty(goods)){
			goods = Goods.dao.findById(getGoodsId());

		}
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}
}
