package com.wtshop.model;

import com.wtshop.model.base.BaseSpecialGoods;
import com.wtshop.util.ObjectUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecialGoods extends BaseSpecialGoods<SpecialGoods> {
	public static final SpecialGoods dao = new SpecialGoods().dao();
	private Product product;

	public Product getProduct() {
		if(ObjectUtils.isEmpty(product)){
			product = Product.dao.findById(getGoodsId());
		}
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}
}
