package com.wtshop.model;

import com.wtshop.model.base.BaseSpecialCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecialCoupon extends BaseSpecialCoupon<SpecialCoupon> {
	public static final SpecialCoupon dao = new SpecialCoupon().dao();
}
