package com.wtshop.model;

import com.wtshop.model.base.BaseStaffMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StaffMember extends BaseStaffMember<StaffMember> {
	public static final StaffMember dao = new StaffMember().dao();
	public StaffMember (){}
	public StaffMember(Long staffId,Long memberId,String organId){
		this.setStaffId(staffId);
		this.setMemberId(memberId);
		this.setStatus(1);
		this.setOrganId(organId);
	}
}
