package com.wtshop.model;

import com.wtshop.model.base.BaseTargetPath;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TargetPath extends BaseTargetPath<TargetPath> {
	public static final TargetPath dao = new TargetPath().dao();
}
