package com.wtshop.model;

import com.wtshop.model.base.BaseTeamManagement;
import com.wtshop.util.ObjectUtils;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeamManagement extends BaseTeamManagement<TeamManagement> {
	public static final TeamManagement dao = new TeamManagement().dao();
	/** 会员等级 */
	private Integer totalPeople;
	public void setTotalPeople(Integer totalPeople) {
		this.totalPeople = totalPeople;
	}
	public Integer getTotalPeople() {
		if (ObjectUtils.isEmpty(totalPeople)) {

			String sql = "SELECT * FROM member s WHERE s.link_share_code LIKE concat('%', '"+getShareCode()+"', '%') and s.share_code is not null";
			List<Member> memeberlist = Member.dao.find(sql);
			totalPeople=memeberlist.size();
		}

		return totalPeople;
	}
}
