package com.wtshop.model;

import com.wtshop.model.base.BaseTeamManagement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeamManagement extends BaseTeamManagement<TeamManagement> {
	public static final TeamManagement dao = new TeamManagement().dao();
}
