package com.wtshop.model;

import com.wtshop.model.base.BaseThemeGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ThemeGoods extends BaseThemeGoods<ThemeGoods> {
	public static final ThemeGoods dao = new ThemeGoods().dao();
}
