package com.wtshop.model;

import com.wtshop.model.base.BaseTicketsnrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ticketsnrecord extends BaseTicketsnrecord<Ticketsnrecord> {
	public static final Ticketsnrecord dao = new Ticketsnrecord().dao();
}
