package com.wtshop.model;

import com.wtshop.model.base.BaseTicketsn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ticketsn extends BaseTicketsn<Ticketsn> {
	public static final Ticketsn dao = new Ticketsn().dao();
}
