package com.wtshop.model;

import com.wtshop.model.base.BaseTicketconfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ticketconfig extends BaseTicketconfig<Ticketconfig> {
	public static final Ticketconfig dao = new Ticketconfig().dao();
}
