package com.wtshop.model;

import com.wtshop.model.base.BaseTicketreceive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ticketreceive extends BaseTicketreceive<Ticketreceive> {
	public static final Ticketreceive dao = new Ticketreceive().dao();

}
