package com.wtshop.model;

import com.wtshop.model.base.BaseVipgoodsHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VipgoodsHistory extends BaseVipgoodsHistory<VipgoodsHistory> {
	public static final VipgoodsHistory dao = new VipgoodsHistory().dao();
}
