package com.wtshop.model;

import com.wtshop.model.base.BaseXcxAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XcxAccount extends BaseXcxAccount<XcxAccount> {
	public static final XcxAccount dao = new XcxAccount().dao();
}
