package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTicketsnrecord<M extends BaseTicketsnrecord<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setTicketSnId(Long ticketSnId) {
		set("ticketSnId", ticketSnId);
	}

	public Long getTicketSnId() {
		return get("ticketSnId");
	}

	public void setTicketId(Long ticketId) {
		set("ticketId", ticketId);
	}

	public Long getTicketId() {
		return get("ticketId");
	}

	public void setTicketName(String ticketName) {
		set("ticketName", ticketName);
	}

	public String getTicketName() {
		return get("ticketName");
	}

	public void setOrderId(Long orderId) {
		set("orderId", orderId);
	}

	public Long getOrderId() {
		return get("orderId");
	}

	public void setCurrentNum(Integer currentNum) {
		set("currentNum", currentNum);
	}

	public Integer getCurrentNum() {
		return get("currentNum");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setMemId(Long memId) {
		set("memId", memId);
	}

	public Long getMemId() {
		return get("memId");
	}

}
