package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReverseAuctionDetail<M extends BaseReverseAuctionDetail<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setReverseAuctionId(Long reverseAuctionId) {
		set("reverse_auction_id", reverseAuctionId);
	}

	public Long getReverseAuctionId() {
		return get("reverse_auction_id");
	}

	public void setProductId(Long productId) {
		set("product_id", productId);
	}

	public Long getProductId() {
		return get("product_id");
	}

	public void setOrders(Integer orders) {
		set("orders", orders);
	}

	public Integer getOrders() {
		return get("orders");
	}

	public void setAuctionOriginalPrice(Double auctionOriginalPrice) {
		set("auction_original_price", auctionOriginalPrice);
	}

	public Double getAuctionOriginalPrice() {
		return get("auction_original_price");
	}

	public void setAuctionStartPrice(Double auctionStartPrice) {
		set("auction_start_price", auctionStartPrice);
	}

	public Double getAuctionStartPrice() {
		return get("auction_start_price");
	}

	public void setAuctionLimitUpPrice(Double auctionLimitUpPrice) {
		set("auction_limit_up_price", auctionLimitUpPrice);
	}

	public Double getAuctionLimitUpPrice() {
		return get("auction_limit_up_price");
	}

	public void setAuctionLimitDownPrice(Double auctionLimitDownPrice) {
		set("auction_limit_down_price", auctionLimitDownPrice);
	}

	public Double getAuctionLimitDownPrice() {
		return get("auction_limit_down_price");
	}

	public void setTotalNum(Integer totalNum) {
		set("total_num", totalNum);
	}

	public Integer getTotalNum() {
		return get("total_num");
	}

	public void setCompleteNum(Integer completeNum) {
		set("complete_num", completeNum);
	}

	public Integer getCompleteNum() {
		return get("complete_num");
	}

	public void setIsFinished(Integer isFinished) {
		set("is_finished", isFinished);
	}

	public Integer getIsFinished() {
		return get("is_finished");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
