package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePromotion<M extends BasePromotion<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setOrders(Integer orders) {
		set("orders", orders);
	}

	public Integer getOrders() {
		return get("orders");
	}

	public void setBeginDate(java.util.Date beginDate) {
		set("begin_date", beginDate);
	}

	public java.util.Date getBeginDate() {
		return get("begin_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setImage(String image) {
		set("image", image);
	}

	public String getImage() {
		return get("image");
	}

	public void setIntroduction(String introduction) {
		set("introduction", introduction);
	}

	public String getIntroduction() {
		return get("introduction");
	}

	public void setIsCouponAllowed(Boolean isCouponAllowed) {
		set("is_coupon_allowed", isCouponAllowed);
	}

	public Boolean getIsCouponAllowed() {
		return get("is_coupon_allowed");
	}

	public void setIsFreeShipping(Boolean isFreeShipping) {
		set("is_free_shipping", isFreeShipping);
	}

	public Boolean getIsFreeShipping() {
		return get("is_free_shipping");
	}

	public void setMaximumPrice(java.math.BigDecimal maximumPrice) {
		set("maximum_price", maximumPrice);
	}

	public java.math.BigDecimal getMaximumPrice() {
		return get("maximum_price");
	}

	public void setMaximumQuantity(Integer maximumQuantity) {
		set("maximum_quantity", maximumQuantity);
	}

	public Integer getMaximumQuantity() {
		return get("maximum_quantity");
	}

	public void setMinimumPrice(java.math.BigDecimal minimumPrice) {
		set("minimum_price", minimumPrice);
	}

	public java.math.BigDecimal getMinimumPrice() {
		return get("minimum_price");
	}

	public void setMinimumQuantity(Integer minimumQuantity) {
		set("minimum_quantity", minimumQuantity);
	}

	public Integer getMinimumQuantity() {
		return get("minimum_quantity");
	}

	public void setTotalMoney(java.math.BigDecimal totalMoney) {
		set("total_money", totalMoney);
	}

	public java.math.BigDecimal getTotalMoney() {
		return get("total_money");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setPointExpression(String pointExpression) {
		set("point_expression", pointExpression);
	}

	public String getPointExpression() {
		return get("point_expression");
	}

	public void setPriceExpression(String priceExpression) {
		set("price_expression", priceExpression);
	}

	public String getPriceExpression() {
		return get("price_expression");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

}
