package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReturns<M extends BaseReturns<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setAddress(String address) {
		set("address", address);
	}

	public String getAddress() {
		return get("address");
	}

	public void setAreaName(String areaName) {
		set("area_name", areaName);
	}

	public String getAreaName() {
		return get("area_name");
	}

	public void setDeliveryCorp(String deliveryCorp) {
		set("delivery_corp", deliveryCorp);
	}

	public String getDeliveryCorp() {
		return get("delivery_corp");
	}

	public void setFreight(java.math.BigDecimal freight) {
		set("freight", freight);
	}

	public java.math.BigDecimal getFreight() {
		return get("freight");
	}

	public void setMemo(String memo) {
		set("memo", memo);
	}

	public String getMemo() {
		return get("memo");
	}

	public void setOperator(String operator) {
		set("operator", operator);
	}

	public String getOperator() {
		return get("operator");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

	public void setShipper(String shipper) {
		set("shipper", shipper);
	}

	public String getShipper() {
		return get("shipper");
	}

	public void setShippingMethod(String shippingMethod) {
		set("shipping_method", shippingMethod);
	}

	public String getShippingMethod() {
		return get("shipping_method");
	}

	public void setSn(String sn) {
		set("sn", sn);
	}

	public String getSn() {
		return get("sn");
	}

	public void setTrackingNo(String trackingNo) {
		set("tracking_no", trackingNo);
	}

	public String getTrackingNo() {
		return get("tracking_no");
	}

	public void setZipCode(String zipCode) {
		set("zip_code", zipCode);
	}

	public String getZipCode() {
		return get("zip_code");
	}

	public void setOrderId(Long orderId) {
		set("order_id", orderId);
	}

	public Long getOrderId() {
		return get("order_id");
	}

	public void setAreaId(Long areaId) {
		set("area_id", areaId);
	}

	public Long getAreaId() {
		return get("area_id");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setCategory(Integer category) {
		set("category", category);
	}

	public Integer getCategory() {
		return get("category");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setIsDelete(Boolean isDelete) {
		set("is_delete", isDelete);
	}

	public Boolean getIsDelete() {
		return get("is_delete");
	}

}
