package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBargainDetail<M extends BaseBargainDetail<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setMasterId(Integer masterId) {
		set("master_id", masterId);
	}

	public Integer getMasterId() {
		return get("master_id");
	}

	public void setProductId(Integer productId) {
		set("product_id", productId);
	}

	public Integer getProductId() {
		return get("product_id");
	}

	public void setBeginPrice(Integer beginPrice) {
		set("begin_price", beginPrice);
	}

	public Integer getBeginPrice() {
		return get("begin_price");
	}

}
