package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseThemeGoods<M extends BaseThemeGoods<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setGoodsthemeId(Long goodsthemeId) {
		set("goodsTheme_id", goodsthemeId);
	}

	public Long getGoodsthemeId() {
		return get("goodsTheme_id");
	}

	public void setGoodsId(Long goodsId) {
		set("goods_id", goodsId);
	}

	public Long getGoodsId() {
		return get("goods_id");
	}

	public void setOrderNo(Long orderNo) {
		set("order_no", orderNo);
	}

	public Long getOrderNo() {
		return get("order_no");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
