package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBargainPersonal<M extends BaseBargainPersonal<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setUserId(Integer userId) {
		set("user_id", userId);
	}

	public Integer getUserId() {
		return get("user_id");
	}

	public void setBargainId(Integer bargainId) {
		set("bargain_id", bargainId);
	}

	public Integer getBargainId() {
		return get("bargain_id");
	}

	public void setNowPrice(Integer nowPrice) {
		set("now_price", nowPrice);
	}

	public Integer getNowPrice() {
		return get("now_price");
	}

}
