package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReferrerConfig<M extends BaseReferrerConfig<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setGoodsNum(Integer goodsNum) {
		set("goods_num", goodsNum);
	}

	public Integer getGoodsNum() {
		return get("goods_num");
	}

	public void setReferrerTime(Long referrerTime) {
		set("referrer_time", referrerTime);
	}

	public Long getReferrerTime() {
		return get("referrer_time");
	}

	public void setPriceDesc(Integer priceDesc) {
		set("price_desc", priceDesc);
	}

	public Integer getPriceDesc() {
		return get("price_desc");
	}

}
