package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCouponCode<M extends BaseCouponCode<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setCode(String code) {
		set("code", code);
	}

	public String getCode() {
		return get("code");
	}

	public void setIsUsed(Boolean isUsed) {
		set("is_used", isUsed);
	}

	public Boolean getIsUsed() {
		return get("is_used");
	}

	public void setUsedDate(java.util.Date usedDate) {
		set("used_date", usedDate);
	}

	public java.util.Date getUsedDate() {
		return get("used_date");
	}

	public void setCouponId(Long couponId) {
		set("coupon_id", couponId);
	}

	public Long getCouponId() {
		return get("coupon_id");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

	public void setReceiveId(Long receiveId) {
		set("receiveId", receiveId);
	}

	public Long getReceiveId() {
		return get("receiveId");
	}

}
