package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActivity<M extends BaseActivity<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setOpporName(String opporName) {
		set("oppor_name", opporName);
	}

	public String getOpporName() {
		return get("oppor_name");
	}

	public void setGoodId(Long goodId) {
		set("good_id", goodId);
	}

	public Long getGoodId() {
		return get("good_id");
	}

	public void setGoodName(String goodName) {
		set("good_name", goodName);
	}

	public String getGoodName() {
		return get("good_name");
	}

	public void setGoodNumber(Integer goodNumber) {
		set("good_number", goodNumber);
	}

	public Integer getGoodNumber() {
		return get("good_number");
	}

	public void setPtNum(Integer ptNum) {
		set("pt_num", ptNum);
	}

	public Integer getPtNum() {
		return get("pt_num");
	}

	public void setBeginDate(java.util.Date beginDate) {
		set("begin_date", beginDate);
	}

	public java.util.Date getBeginDate() {
		return get("begin_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setForeNumber(Integer foreNumber) {
		set("fore_number", foreNumber);
	}

	public Integer getForeNumber() {
		return get("fore_number");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

	public void setNowNumber(Integer nowNumber) {
		set("now_number", nowNumber);
	}

	public Integer getNowNumber() {
		return get("now_number");
	}

	public void setOrderId(Long orderId) {
		set("order_id", orderId);
	}

	public Long getOrderId() {
		return get("order_id");
	}

	public void setStates(String states) {
		set("states", states);
	}

	public String getStates() {
		return get("states");
	}


	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}



	public void setOneMaxGoods(Integer oneMaxGoods) {
		set("one_max_goods", oneMaxGoods);
	}

	public Integer getOneMaxGoods() {
		return get("one_max_goods");
	}

	public void setLotteryExp(java.util.Date lotteryExp) {
		set("lottery_exp", lotteryExp);
	}

	public java.util.Date getLotteryExp() {
		return get("lottery_exp");
	}

	public void setPoint(java.math.BigDecimal point) {
		set("point", point);
	}

	public java.math.BigDecimal getPoint() {
		return get("point");
	}

	public void setLuckyNumber(Integer luckyNumber) {
		set("lucky_number", luckyNumber);
	}

	public Integer getLuckyNumber() {
		return get("lucky_number");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
