package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShippingMethod<M extends BaseShippingMethod<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setOrders(Integer orders) {
		set("orders", orders);
	}

	public Integer getOrders() {
		return get("orders");
	}

	public void setContinueWeight(Integer continueWeight) {
		set("continue_weight", continueWeight);
	}

	public Integer getContinueWeight() {
		return get("continue_weight");
	}

	public void setDefaultMoney(java.math.BigDecimal defaultMoney) {
		set("default_money", defaultMoney);
	}

	public java.math.BigDecimal getDefaultMoney() {
		return get("default_money");
	}

	public void setDefaultContinuePrice(java.math.BigDecimal defaultContinuePrice) {
		set("default_continue_price", defaultContinuePrice);
	}

	public java.math.BigDecimal getDefaultContinuePrice() {
		return get("default_continue_price");
	}

	public void setDefaultFirstPrice(java.math.BigDecimal defaultFirstPrice) {
		set("default_first_price", defaultFirstPrice);
	}

	public java.math.BigDecimal getDefaultFirstPrice() {
		return get("default_first_price");
	}

	public void setDescription(String description) {
		set("description", description);
	}

	public String getDescription() {
		return get("description");
	}

	public void setFirstWeight(Integer firstWeight) {
		set("first_weight", firstWeight);
	}

	public Integer getFirstWeight() {
		return get("first_weight");
	}

	public void setIcon(String icon) {
		set("icon", icon);
	}

	public String getIcon() {
		return get("icon");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setDefaultDeliveryCorpId(Long defaultDeliveryCorpId) {
		set("default_delivery_corp_id", defaultDeliveryCorpId);
	}

	public Long getDefaultDeliveryCorpId() {
		return get("default_delivery_corp_id");
	}

}
