package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRaffle<M extends BaseRaffle<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

	public void setActivityId(Long activityId) {
		set("activity_id", activityId);
	}

	public Long getActivityId() {
		return get("activity_id");
	}

	public void setIsReal(Integer isReal) {
		set("isReal", isReal);
	}

	public Integer getIsReal() {
		return get("isReal");
	}

	public void setActivityProductId(Long activityProductId) {
		set("activityProductId", activityProductId);
	}

	public Long getActivityProductId() {
		return get("activityProductId");
	}

	public void setPoint(java.math.BigDecimal point) {
		set("point", point);
	}

	public java.math.BigDecimal getPoint() {
		return get("point");
	}

	public void setIssue(Integer issue) {
		set("issue", issue);
	}

	public Integer getIssue() {
		return get("issue");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setSn(String sn) {
		set("sn", sn);
	}

	public String getSn() {
		return get("sn");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

}
