package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setAddress(String address) {
		set("address", address);
	}

	public String getAddress() {
		return get("address");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setAmountPaid(java.math.BigDecimal amountPaid) {
		set("amount_paid", amountPaid);
	}

	public java.math.BigDecimal getAmountPaid() {
		return get("amount_paid");
	}

	public void setWeixinPaid(java.math.BigDecimal weixinPaid) {
		set("weiXin_paid", weixinPaid);
	}

	public java.math.BigDecimal getWeixinPaid() {
		return get("weiXin_paid");
	}

	public void setAliPaid(java.math.BigDecimal aliPaid) {
		set("aLi_paid", aliPaid);
	}

	public java.math.BigDecimal getAliPaid() {
		return get("aLi_paid");
	}

	public void setOrderNo(String orderNo) {
		set("order_no", orderNo);
	}

	public String getOrderNo() {
		return get("order_no");
	}

	public void setReturnCopyPaid(java.math.BigDecimal returnCopyPaid) {
		set("return_copy_paid", returnCopyPaid);
	}

	public java.math.BigDecimal getReturnCopyPaid() {
		return get("return_copy_paid");
	}

	public void setMiaobiPaid(java.math.BigDecimal miaobiPaid) {
		set("miaobi_paid", miaobiPaid);
	}

	public java.math.BigDecimal getMiaobiPaid() {
		return get("miaobi_paid");
	}

	public void setAreaName(String areaName) {
		set("area_name", areaName);
	}

	public String getAreaName() {
		return get("area_name");
	}

	public void setCompleteDate(java.util.Date completeDate) {
		set("complete_date", completeDate);
	}

	public java.util.Date getCompleteDate() {
		return get("complete_date");
	}

	public void setConsignee(String consignee) {
		set("consignee", consignee);
	}

	public String getConsignee() {
		return get("consignee");
	}

	public void setCouponDiscount(java.math.BigDecimal couponDiscount) {
		set("coupon_discount", couponDiscount);
	}

	public java.math.BigDecimal getCouponDiscount() {
		return get("coupon_discount");
	}

	public void setExchangePoint(Long exchangePoint) {
		set("exchange_point", exchangePoint);
	}

	public Long getExchangePoint() {
		return get("exchange_point");
	}

	public void setExpire(java.util.Date expire) {
		set("expire", expire);
	}

	public java.util.Date getExpire() {
		return get("expire");
	}

	public void setFee(java.math.BigDecimal fee) {
		set("fee", fee);
	}

	public java.math.BigDecimal getFee() {
		return get("fee");
	}

	public void setFreight(java.math.BigDecimal freight) {
		set("freight", freight);
	}

	public java.math.BigDecimal getFreight() {
		return get("freight");
	}

	public void setInvoiceContent(String invoiceContent) {
		set("invoice_content", invoiceContent);
	}

	public String getInvoiceContent() {
		return get("invoice_content");
	}

	public void setInvoiceTitle(String invoiceTitle) {
		set("invoice_title", invoiceTitle);
	}

	public String getInvoiceTitle() {
		return get("invoice_title");
	}

	public void setIsAllocatedStock(Boolean isAllocatedStock) {
		set("is_allocated_stock", isAllocatedStock);
	}

	public Boolean getIsAllocatedStock() {
		return get("is_allocated_stock");
	}

	public void setIsExchangePoint(Boolean isExchangePoint) {
		set("is_exchange_point", isExchangePoint);
	}

	public Boolean getIsExchangePoint() {
		return get("is_exchange_point");
	}

	public void setIsUseCouponCode(Boolean isUseCouponCode) {
		set("is_use_coupon_code", isUseCouponCode);
	}

	public Boolean getIsUseCouponCode() {
		return get("is_use_coupon_code");
	}

	public void setLockExpire(java.util.Date lockExpire) {
		set("lock_expire", lockExpire);
	}

	public java.util.Date getLockExpire() {
		return get("lock_expire");
	}

	public void setLockKey(String lockKey) {
		set("lock_key", lockKey);
	}

	public String getLockKey() {
		return get("lock_key");
	}

	public void setMemo(String memo) {
		set("memo", memo);
	}

	public String getMemo() {
		return get("memo");
	}

	public void setOffsetAmount(java.math.BigDecimal offsetAmount) {
		set("offset_amount", offsetAmount);
	}

	public java.math.BigDecimal getOffsetAmount() {
		return get("offset_amount");
	}

	public void setPaymentMethodName(String paymentMethodName) {
		set("payment_method_name", paymentMethodName);
	}

	public String getPaymentMethodName() {
		return get("payment_method_name");
	}

	public void setPaymentMethodType(Integer paymentMethodType) {
		set("payment_method_type", paymentMethodType);
	}

	public Integer getPaymentMethodType() {
		return get("payment_method_type");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setPromotionDiscount(java.math.BigDecimal promotionDiscount) {
		set("promotion_discount", promotionDiscount);
	}

	public java.math.BigDecimal getPromotionDiscount() {
		return get("promotion_discount");
	}

	public void setPromotionNames(String promotionNames) {
		set("promotion_names", promotionNames);
	}

	public String getPromotionNames() {
		return get("promotion_names");
	}

	public void setQuantity(Integer quantity) {
		set("quantity", quantity);
	}

	public Integer getQuantity() {
		return get("quantity");
	}

	public void setRefundAmount(java.math.BigDecimal refundAmount) {
		set("refund_amount", refundAmount);
	}

	public java.math.BigDecimal getRefundAmount() {
		return get("refund_amount");
	}

	public void setReturnedQuantity(Integer returnedQuantity) {
		set("returned_quantity", returnedQuantity);
	}

	public Integer getReturnedQuantity() {
		return get("returned_quantity");
	}

	public void setRewardPoint(Long rewardPoint) {
		set("reward_point", rewardPoint);
	}

	public Long getRewardPoint() {
		return get("reward_point");
	}

	public void setShippedQuantity(Integer shippedQuantity) {
		set("shipped_quantity", shippedQuantity);
	}

	public Integer getShippedQuantity() {
		return get("shipped_quantity");
	}

	public void setShippingMethodName(String shippingMethodName) {
		set("shipping_method_name", shippingMethodName);
	}

	public String getShippingMethodName() {
		return get("shipping_method_name");
	}

	public void setSn(String sn) {
		set("sn", sn);
	}

	public String getSn() {
		return get("sn");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setTax(java.math.BigDecimal tax) {
		set("tax", tax);
	}

	public java.math.BigDecimal getTax() {
		return get("tax");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setWeight(Integer weight) {
		set("weight", weight);
	}

	public Integer getWeight() {
		return get("weight");
	}

	public void setZipCode(String zipCode) {
		set("zip_code", zipCode);
	}

	public String getZipCode() {
		return get("zip_code");
	}

	public void setAreaId(Long areaId) {
		set("area_id", areaId);
	}

	public Long getAreaId() {
		return get("area_id");
	}

	public void setCouponCodeId(Long couponCodeId) {
		set("coupon_code_id", couponCodeId);
	}

	public Long getCouponCodeId() {
		return get("coupon_code_id");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

	public void setPaymentMethodId(Long paymentMethodId) {
		set("payment_method_id", paymentMethodId);
	}

	public Long getPaymentMethodId() {
		return get("payment_method_id");
	}

	public void setShippingMethodId(Long shippingMethodId) {
		set("shipping_method_id", shippingMethodId);
	}

	public Long getShippingMethodId() {
		return get("shipping_method_id");
	}

	public void setIsDelete(Boolean isDelete) {
		set("is_delete", isDelete);
	}

	public Boolean getIsDelete() {
		return get("is_delete");
	}

	public void setIsVip(Boolean isVip) {
		set("is_vip", isVip);
	}

	public Boolean getIsVip() {
		return get("is_vip");
	}

	public void setActOrderId(String actOrderId) {
		set("actOrderId", actOrderId);
	}

	public String getActOrderId() {
		return get("actOrderId");
	}

	public void setIsCommission(Boolean isCommission) {
		set("is_commission", isCommission);
	}

	public Boolean getIsCommission() {
		return get("is_commission");
	}

	public void setIsInvoice(Boolean isInvoice) {
		set("isInvoice", isInvoice);
	}

	public Boolean getIsInvoice() {
		return get("isInvoice");
	}

	public void setIsPersonal(Boolean isPersonal) {
		set("isPersonal", isPersonal);
	}

	public Boolean getIsPersonal() {
		return get("isPersonal");
	}

	public void setTaxNumber(String taxNumber) {
		set("taxNumber", taxNumber);
	}

	public String getTaxNumber() {
		return get("taxNumber");
	}

	public void setCompanyName(String companyName) {
		set("companyName", companyName);
	}

	public String getCompanyName() {
		return get("companyName");
	}

	public void setFightgroupId(Long fightgroupId) {
		set("fightgroup_id", fightgroupId);
	}

	public Long getFightgroupId() {
		return get("fightgroup_id");
	}

	public void setGroupbuyId(Long groupbuyId) {
		set("groupbuy_id", groupbuyId);
	}

	public Long getGroupbuyId() {
		return get("groupbuy_id");
	}

	public void setIsSinglepurchase(Boolean isSinglepurchase) {
		set("is_singlepurchase", isSinglepurchase);
	}

	public Boolean getIsSinglepurchase() {
		return get("is_singlepurchase");
	}

	public void setOnShareCode(String onShareCode) {
		set("on_share_code", onShareCode);
	}

	public String getOnShareCode() {
		return get("on_share_code");
	}

	public void setCommissionRate(Double commissionRate) {
		set("commission_rate", commissionRate);
	}

	public Double getCommissionRate() {
		return get("commission_rate");
	}

	public void setShareCode(String shareCode) {
		set("share_code", shareCode);
	}

	public String getShareCode() {
		return get("share_code");
	}

	public void setIdentifierId(Long identifierId) {
		set("identifier_id", identifierId);
	}

	public Long getIdentifierId() {
		return get("identifier_id");
	}

	public void setSpecialCouponPrice(java.math.BigDecimal specialCouponPrice) {
		set("specialCouponPrice", specialCouponPrice);
	}

	public java.math.BigDecimal getSpecialCouponPrice() {
		return get("specialCouponPrice");
	}

	public void setSpecialcoupId(String specialcoupId) {
		set("sPecialCoup_Id", specialcoupId);
	}

	public String getSpecialcoupId() {
		return get("sPecialCoup_Id");
	}

	public void setIntegralPaid(java.math.BigDecimal integralPaid) {
		set("integral_paid", integralPaid);
	}

	public java.math.BigDecimal getIntegralPaid() {
		return get("integral_paid");
	}

	public void setIntegralGift(java.math.BigDecimal integralGift) {
		set("integral_gift", integralGift);
	}

	public java.math.BigDecimal getIntegralGift() {
		return get("integral_gift");
	}

	public void setIntegral(java.math.BigDecimal integral) {
		set("integral", integral);
	}

	public java.math.BigDecimal getIntegral() {
		return get("integral");
	}

}
