package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppManage<M extends BaseAppManage<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setAppName(String appName) {
		set("appName", appName);
	}

	public String getAppName() {
		return get("appName");
	}

	public void setAppId(String appId) {
		set("appId", appId);
	}

	public String getAppId() {
		return get("appId");
	}

	public void setAppKey(String appKey) {
		set("appKey", appKey);
	}

	public String getAppKey() {
		return get("appKey");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setIpWhiteList(String ipWhiteList) {
		set("ipWhiteList", ipWhiteList);
	}

	public String getIpWhiteList() {
		return get("ipWhiteList");
	}

}
