package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setAuthor(String author) {
		set("author", author);
	}

	public String getAuthor() {
		return get("author");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return get("content");
	}

	public void setGenerateMethod(Integer generateMethod) {
		set("generate_method", generateMethod);
	}

	public Integer getGenerateMethod() {
		return get("generate_method");
	}

	public void setHits(Long hits) {
		set("hits", hits);
	}

	public Long getHits() {
		return get("hits");
	}

	public void setIsPublication(Boolean isPublication) {
		set("is_publication", isPublication);
	}

	public Boolean getIsPublication() {
		return get("is_publication");
	}

	public void setIsTop(Boolean isTop) {
		set("is_top", isTop);
	}

	public Boolean getIsTop() {
		return get("is_top");
	}

	public void setSeoDescription(String seoDescription) {
		set("seo_description", seoDescription);
	}

	public String getSeoDescription() {
		return get("seo_description");
	}

	public void setSeoKeywords(String seoKeywords) {
		set("seo_keywords", seoKeywords);
	}

	public String getSeoKeywords() {
		return get("seo_keywords");
	}

	public void setSeoTitle(String seoTitle) {
		set("seo_title", seoTitle);
	}

	public String getSeoTitle() {
		return get("seo_title");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setArticleCategoryId(Long articleCategoryId) {
		set("article_category_id", articleCategoryId);
	}

	public Long getArticleCategoryId() {
		return get("article_category_id");
	}

}
