package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAreaDescribe<M extends BaseAreaDescribe<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setAreaId(Long areaId) {
		set("areaId", areaId);
	}

	public Long getAreaId() {
		return get("areaId");
	}

	public void setEntrepotName(String entrepotName) {
		set("entrepot_name", entrepotName);
	}

	public String getEntrepotName() {
		return get("entrepot_name");
	}

	public void setEntrepotMessage(String entrepotMessage) {
		set("entrepot_message", entrepotMessage);
	}

	public String getEntrepotMessage() {
		return get("entrepot_message");
	}

	public void setReceivingBegintime(String receivingBegintime) {
		set("receiving_beginTime", receivingBegintime);
	}

	public String getReceivingBegintime() {
		return get("receiving_beginTime");
	}

	public void setReceivingEndtime(Integer receivingEndtime) {
		set("receiving_endTime", receivingEndtime);
	}

	public Integer getReceivingEndtime() {
		return get("receiving_endTime");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

}
