package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePromotionGift<M extends BasePromotionGift<M>> extends Model<M> implements IBean {

	public void setGiftPromotions(Long giftPromotions) {
		set("gift_promotions", giftPromotions);
	}

	public Long getGiftPromotions() {
		return get("gift_promotions");
	}

	public void setGifts(Long gifts) {
		set("gifts", gifts);
	}

	public Long getGifts() {
		return get("gifts");
	}

}
