package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderItem<M extends BaseOrderItem<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setIsDelivery(Boolean isDelivery) {
		set("is_delivery", isDelivery);
	}

	public Boolean getIsDelivery() {
		return get("is_delivery");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setQuantity(Integer quantity) {
		set("quantity", quantity);
	}

	public Integer getQuantity() {
		return get("quantity");
	}

	public void setReturnedQuantity(Integer returnedQuantity) {
		set("returned_quantity", returnedQuantity);
	}

	public Integer getReturnedQuantity() {
		return get("returned_quantity");
	}

	public void setShippedQuantity(Integer shippedQuantity) {
		set("shipped_quantity", shippedQuantity);
	}

	public Integer getShippedQuantity() {
		return get("shipped_quantity");
	}

	public void setSn(String sn) {
		set("sn", sn);
	}

	public String getSn() {
		return get("sn");
	}

	public void setSpecifications(String specifications) {
		set("specifications", specifications);
	}

	public String getSpecifications() {
		return get("specifications");
	}

	public void setThumbnail(String thumbnail) {
		set("thumbnail", thumbnail);
	}

	public String getThumbnail() {
		return get("thumbnail");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setWeight(Integer weight) {
		set("weight", weight);
	}

	public Integer getWeight() {
		return get("weight");
	}

	public void setIsReview(Boolean isReview) {
		set("is_review", isReview);
	}

	public Boolean getIsReview() {
		return get("is_review");
	}

	public void setOrderId(Long orderId) {
		set("order_id", orderId);
	}

	public Long getOrderId() {
		return get("order_id");
	}

	public void setProductId(Long productId) {
		set("product_id", productId);
	}

	public Long getProductId() {
		return get("product_id");
	}

	public void setActitemId(Long actitemId) {
		set("actItem_id", actitemId);
	}

	public Long getActitemId() {
		return get("actItem_id");
	}

}
