package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMrmfShop<M extends BaseMrmfShop<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setCommission(java.math.BigDecimal commission) {
		set("commission", commission);
	}

	public java.math.BigDecimal getCommission() {
		return get("commission");
	}

	public void setPrestore(java.math.BigDecimal prestore) {
		set("prestore", prestore);
	}

	public java.math.BigDecimal getPrestore() {
		return get("prestore");
	}

	public void setOrganId(String organId) {
		set("organ_id", organId);
	}

	public String getOrganId() {
		return get("organ_id");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

	public void setAttributeValue1(String attributeValue1) {
		set("attribute_value1", attributeValue1);
	}

	public String getAttributeValue1() {
		return get("attribute_value1");
	}

	public void setAttributeValue2(String attributeValue2) {
		set("attribute_value2", attributeValue2);
	}

	public String getAttributeValue2() {
		return get("attribute_value2");
	}

	public void setAttributeValue3(String attributeValue3) {
		set("attribute_value3", attributeValue3);
	}

	public String getAttributeValue3() {
		return get("attribute_value3");
	}

	public void setAttributeValue4(String attributeValue4) {
		set("attribute_value4", attributeValue4);
	}

	public String getAttributeValue4() {
		return get("attribute_value4");
	}

	public void setAttributeValue5(String attributeValue5) {
		set("attribute_value5", attributeValue5);
	}

	public String getAttributeValue5() {
		return get("attribute_value5");
	}

}
