package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRefunds<M extends BaseRefunds<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setBalanceReturn(java.math.BigDecimal balanceReturn) {
		set("balance_return", balanceReturn);
	}

	public java.math.BigDecimal getBalanceReturn() {
		return get("balance_return");
	}

	public void setMemo(String memo) {
		set("memo", memo);
	}

	public String getMemo() {
		return get("memo");
	}

	public void setOperator(String operator) {
		set("operator", operator);
	}

	public String getOperator() {
		return get("operator");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

	public void setSn(String sn) {
		set("sn", sn);
	}

	public String getSn() {
		return get("sn");
	}

	public void setOrderId(Long orderId) {
		set("order_id", orderId);
	}

	public Long getOrderId() {
		return get("order_id");
	}

	public void setReturnsId(Long returnsId) {
		set("returns_id", returnsId);
	}

	public Long getReturnsId() {
		return get("returns_id");
	}

}
