package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsOperFlow<M extends BaseGoodsOperFlow<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setInfo(String info) {
		set("info", info);
	}

	public String getInfo() {
		return get("info");
	}

	public void setSubmitId(Long submitId) {
		set("submitId", submitId);
	}

	public Long getSubmitId() {
		return get("submitId");
	}

	public void setVerifyId(Long verifyId) {
		set("verifyId", verifyId);
	}

	public Long getVerifyId() {
		return get("verifyId");
	}

	public void setVerifyTime(java.util.Date verifyTime) {
		set("verifyTime", verifyTime);
	}

	public java.util.Date getVerifyTime() {
		return get("verifyTime");
	}

	public void setVerifyResult(Integer verifyResult) {
		set("verifyResult", verifyResult);
	}

	public Integer getVerifyResult() {
		return get("verifyResult");
	}

	public void setVerifySuggest(String verifySuggest) {
		set("verifySuggest", verifySuggest);
	}

	public String getVerifySuggest() {
		return get("verifySuggest");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setGoodsId(Long goodsId) {
		set("goodsId", goodsId);
	}

	public Long getGoodsId() {
		return get("goodsId");
	}

	public void setOptType(Integer optType) {
		set("optType", optType);
	}

	public Integer getOptType() {
		return get("optType");
	}

}
