package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShippingItem<M extends BaseShippingItem<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setIsDelivery(Boolean isDelivery) {
		set("is_delivery", isDelivery);
	}

	public Boolean getIsDelivery() {
		return get("is_delivery");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setQuantity(Integer quantity) {
		set("quantity", quantity);
	}

	public Integer getQuantity() {
		return get("quantity");
	}

	public void setSn(String sn) {
		set("sn", sn);
	}

	public String getSn() {
		return get("sn");
	}

	public void setSpecifications(String specifications) {
		set("specifications", specifications);
	}

	public String getSpecifications() {
		return get("specifications");
	}

	public void setProductId(Long productId) {
		set("product_id", productId);
	}

	public Long getProductId() {
		return get("product_id");
	}

	public void setShippingId(Long shippingId) {
		set("shipping_id", shippingId);
	}

	public Long getShippingId() {
		return get("shipping_id");
	}

}
