package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTicketreceive<M extends BaseTicketreceive<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setMemberId(Long MemberId) {
		set("MemberId", MemberId);
	}

	public Long getMemberId() {
		return get("MemberId");
	}

	public void setTicketsnrecordId(Long ticketsnrecordId) {
		set("ticketsnrecordId", ticketsnrecordId);
	}

	public Long getTicketsnrecordId() {
		return get("ticketsnrecordId");
	}

	public void setRealSTime(java.util.Date realSTime) {
		set("realSTime", realSTime);
	}

	public java.util.Date getRealSTime() {
		return get("realSTime");
	}

	public void setRealETime(java.util.Date realETime) {
		set("realETime", realETime);
	}

	public java.util.Date getRealETime() {
		return get("realETime");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setModulus(String modulus) {
		set("modulus", modulus);
	}

	public String getModulus() {
		return get("modulus");
	}

	public void setMoney(String money) {
		set("money", money);
	}

	public String getMoney() {
		return get("money");
	}

	public void setCondition(String condition) {
		set("condition", condition);
	}

	public String getCondition() {
		return get("condition");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setProductId(Long productId) {
		set("product_id", productId);
	}

	public Long getProductId() {
		return get("product_id");
	}

	public void setProductCategoryId(Long productCategoryId) {
		set("product_category_id", productCategoryId);
	}

	public Long getProductCategoryId() {
		return get("product_category_id");
	}

	public void setImage(String image) {
		set("image", image);
	}

	public String getImage() {
		return get("image");
	}

	public void setDesc(String desc) {
		set("desc", desc);
	}

	public String getDesc() {
		return get("desc");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setIsEnabled(Boolean isEnabled) {
		set("is_enabled", isEnabled);
	}

	public Boolean getIsEnabled() {
		return get("is_enabled");
	}

	public void setIsExchange(Boolean isExchange) {
		set("is_exchange", isExchange);
	}

	public Boolean getIsExchange() {
		return get("is_exchange");
	}

}
