package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePaymentLog<M extends BasePaymentLog<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setFee(java.math.BigDecimal fee) {
		set("fee", fee);
	}

	public java.math.BigDecimal getFee() {
		return get("fee");
	}

	public void setPaymentPluginId(String paymentPluginId) {
		set("payment_plugin_id", paymentPluginId);
	}

	public String getPaymentPluginId() {
		return get("payment_plugin_id");
	}

	public void setPaymentPluginName(String paymentPluginName) {
		set("payment_plugin_name", paymentPluginName);
	}

	public String getPaymentPluginName() {
		return get("payment_plugin_name");
	}

	public void setSn(String sn) {
		set("sn", sn);
	}

	public String getSn() {
		return get("sn");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

	public void setOrderId(Long orderId) {
		set("order_id", orderId);
	}

	public Long getOrderId() {
		return get("order_id");
	}

}
