package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setAllocatedStock(Integer allocatedStock) {
		set("allocated_stock", allocatedStock);
	}

	public Integer getAllocatedStock() {
		return get("allocated_stock");
	}

	public void setCost(java.math.BigDecimal cost) {
		set("cost", cost);
	}

	public java.math.BigDecimal getCost() {
		return get("cost");
	}

	public void setExchangePoint(Long exchangePoint) {
		set("exchange_point", exchangePoint);
	}

	public Long getExchangePoint() {
		return get("exchange_point");
	}

	public void setIsDefault(Boolean isDefault) {
		set("is_default", isDefault);
	}

	public Boolean getIsDefault() {
		return get("is_default");
	}

	public void setMarketPrice(java.math.BigDecimal marketPrice) {
		set("market_price", marketPrice);
	}

	public java.math.BigDecimal getMarketPrice() {
		return get("market_price");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setRewardPoint(Long rewardPoint) {
		set("reward_point", rewardPoint);
	}

	public Long getRewardPoint() {
		return get("reward_point");
	}

	public void setSn(String sn) {
		set("sn", sn);
	}

	public String getSn() {
		return get("sn");
	}

	public void setSpecificationValues(String specificationValues) {
		set("specification_values", specificationValues);
	}

	public String getSpecificationValues() {
		return get("specification_values");
	}

	public void setStock(Integer stock) {
		set("stock", stock);
	}

	public Integer getStock() {
		return get("stock");
	}

	public void setGoodsId(Long goodsId) {
		set("goods_id", goodsId);
	}

	public Long getGoodsId() {
		return get("goods_id");
	}

	public void setCommissionRate(Double commissionRate) {
		set("commission_rate", commissionRate);
	}

	public Double getCommissionRate() {
		return get("commission_rate");
	}

}
