package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBargainHistroy<M extends BaseBargainHistroy<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setReverseauctionId(Long reverseauctionId) {
		set("reverseauction_id", reverseauctionId);
	}

	public Long getReverseauctionId() {
		return get("reverseauction_id");
	}

	public void setReverseauctionDetailId(Long reverseauctionDetailId) {
		set("reverseauction_detail_id", reverseauctionDetailId);
	}

	public Long getReverseauctionDetailId() {
		return get("reverseauction_detail_id");
	}

	public void setCurrentPrice(Double currentPrice) {
		set("current_price", currentPrice);
	}

	public Double getCurrentPrice() {
		return get("current_price");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setOrders(Integer orders) {
		set("orders", orders);
	}

	public Integer getOrders() {
		return get("orders");
	}

}
