package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFreeApply<M extends BaseFreeApply<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setMasterId(Long masterId) {
		set("master_id", masterId);
	}

	public Long getMasterId() {
		return get("master_id");
	}

	public void setUserId(Long userId) {
		set("user_id", userId);
	}

	public Long getUserId() {
		return get("user_id");
	}

	public void setIsSuccess(Integer isSuccess) {
		set("is_success", isSuccess);
	}

	public Integer getIsSuccess() {
		return get("is_success");
	}

	public void setIsCommit(Integer isCommit) {
		set("is_commit", isCommit);
	}

	public Integer getIsCommit() {
		return get("is_commit");
	}

	public void setReport(Integer report) {
		set("report", report);
	}

	public Integer getReport() {
		return get("report");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setOrders(Integer orders) {
		set("orders", orders);
	}

	public Integer getOrders() {
		return get("orders");
	}

}
