package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVipgoodsHistory<M extends BaseVipgoodsHistory<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setImage(String image) {
		set("image", image);
	}

	public String getImage() {
		return get("image");
	}

	public void setGoodsName(String goodsName) {
		set("goods_name", goodsName);
	}

	public String getGoodsName() {
		return get("goods_name");
	}

	public void setGoodsPrice(java.math.BigDecimal goodsPrice) {
		set("goods_price", goodsPrice);
	}

	public java.math.BigDecimal getGoodsPrice() {
		return get("goods_price");
	}

	public void setQuantity(Integer quantity) {
		set("quantity", quantity);
	}

	public Integer getQuantity() {
		return get("quantity");
	}

	public void setOrganName(String organName) {
		set("organ_name", organName);
	}

	public String getOrganName() {
		return get("organ_name");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setDesc(String desc) {
		set("desc", desc);
	}

	public String getDesc() {
		return get("desc");
	}

	public void setOrganId(String organId) {
		set("organ_id", organId);
	}

	public String getOrganId() {
		return get("organ_id");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

	public void setGoodsId(Long goodsId) {
		set("goods_id", goodsId);
	}

	public Long getGoodsId() {
		return get("goods_id");
	}

	public void setReceiverId(Long receiverId) {
		set("receiver_id", receiverId);
	}

	public Long getReceiverId() {
		return get("receiver_id");
	}

	public void setSn(String sn) {
		set("sn", sn);
	}

	public String getSn() {
		return get("sn");
	}

	public void setMemberName(String memberName) {
		set("member_name", memberName);
	}

	public String getMemberName() {
		return get("member_name");
	}

	public void setOrderId(Long orderId) {
		set("order_id", orderId);
	}

	public Long getOrderId() {
		return get("order_id");
	}

}
