package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeliveryTemplate<M extends BaseDeliveryTemplate<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setBackground(String background) {
		set("background", background);
	}

	public String getBackground() {
		return get("background");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return get("content");
	}

	public void setHeight(Integer height) {
		set("height", height);
	}

	public Integer getHeight() {
		return get("height");
	}

	public void setIsDefault(Boolean isDefault) {
		set("is_default", isDefault);
	}

	public Boolean getIsDefault() {
		return get("is_default");
	}

	public void setMemo(String memo) {
		set("memo", memo);
	}

	public String getMemo() {
		return get("memo");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setOffsetx(Integer offsetx) {
		set("offsetx", offsetx);
	}

	public Integer getOffsetx() {
		return get("offsetx");
	}

	public void setOffsety(Integer offsety) {
		set("offsety", offsety);
	}

	public Integer getOffsety() {
		return get("offsety");
	}

	public void setWidth(Integer width) {
		set("width", width);
	}

	public Integer getWidth() {
		return get("width");
	}

}
