package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFightGroup<M extends BaseFightGroup<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setOrders(Integer orders) {
		set("orders", orders);
	}

	public Integer getOrders() {
		return get("orders");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setPrice(Double price) {
		set("price", price);
	}

	public Double getPrice() {
		return get("price");
	}

	public void setUniprice(Double uniprice) {
		set("uniprice", uniprice);
	}

	public Double getUniprice() {
		return get("uniprice");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setRule(String rule) {
		set("rule", rule);
	}

	public String getRule() {
		return get("rule");
	}

	public void setImage(String image) {
		set("image", image);
	}

	public String getImage() {
		return get("image");
	}

	public void setExplain(String explain) {
		set("explain", explain);
	}

	public String getExplain() {
		return get("explain");
	}

	public void setProductId(Integer productId) {
		set("productId", productId);
	}

	public Integer getProductId() {
		return get("productId");
	}

	public void setSales(Integer sales) {
		set("sales", sales);
	}

	public Integer getSales() {
		return get("sales");
	}

	public void setDispatchprice(Double dispatchprice) {
		set("dispatchprice", dispatchprice);
	}

	public Double getDispatchprice() {
		return get("dispatchprice");
	}

	public void setGroupnum(Integer groupnum) {
		set("groupnum", groupnum);
	}

	public Integer getGroupnum() {
		return get("groupnum");
	}

	public void setEndtime(Integer endtime) {
		set("endtime", endtime);
	}

	public Integer getEndtime() {
		return get("endtime");
	}

}
