package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTargetPath<M extends BaseTargetPath<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setTargetPath(String targetPath) {
		set("target_path", targetPath);
	}

	public String getTargetPath() {
		return get("target_path");
	}

	public void setUrltype(Integer urltype) {
		set("urltype", urltype);
	}

	public Integer getUrltype() {
		return get("urltype");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setOrders(Long orders) {
		set("orders", orders);
	}

	public Long getOrders() {
		return get("orders");
	}

	public void setLevelState(Long levelState) {
		set("level_state", levelState);
	}

	public Long getLevelState() {
		return get("level_state");
	}

	public void setGoodsId(Long goodsId) {
		set("goodsId", goodsId);
	}

	public Long getGoodsId() {
		return get("goodsId");
	}

	public void setGoodsName(String goodsName) {
		set("goodsName", goodsName);
	}

	public String getGoodsName() {
		return get("goodsName");
	}

}
