package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTicket<M extends BaseTicket<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setConfigId(Long configId) {
		set("config_id", configId);
	}

	public Long getConfigId() {
		return get("config_id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setModulus(String modulus) {
		set("modulus", modulus);
	}

	public String getModulus() {
		return get("modulus");
	}

	public void setMoney(String money) {
		set("money", money);
	}

	public String getMoney() {
		return get("money");
	}

	public void setCondition(String condition) {
		set("condition", condition);
	}

	public String getCondition() {
		return get("condition");
	}

	public void setProductCategoryId(Long productCategoryId) {
		set("product_category_id", productCategoryId);
	}

	public Long getProductCategoryId() {
		return get("product_category_id");
	}

	public void setImage(String image) {
		set("image", image);
	}

	public String getImage() {
		return get("image");
	}

	public void setBeginDate(java.util.Date beginDate) {
		set("begin_date", beginDate);
	}

	public java.util.Date getBeginDate() {
		return get("begin_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setEffectiveDay(Integer effectiveDay) {
		set("effectiveDay", effectiveDay);
	}

	public Integer getEffectiveDay() {
		return get("effectiveDay");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setIntroduction(String introduction) {
		set("introduction", introduction);
	}

	public String getIntroduction() {
		return get("introduction");
	}

	public void setIsEnabled(Boolean isEnabled) {
		set("is_enabled", isEnabled);
	}

	public Boolean getIsEnabled() {
		return get("is_enabled");
	}

	public void setIsExchange(Boolean isExchange) {
		set("is_exchange", isExchange);
	}

	public Boolean getIsExchange() {
		return get("is_exchange");
	}

	public void setMaximumPrice(java.math.BigDecimal maximumPrice) {
		set("maximum_price", maximumPrice);
	}

	public java.math.BigDecimal getMaximumPrice() {
		return get("maximum_price");
	}

	public void setMaximumQuantity(Integer maximumQuantity) {
		set("maximum_quantity", maximumQuantity);
	}

	public Integer getMaximumQuantity() {
		return get("maximum_quantity");
	}

	public void setMinimumPrice(java.math.BigDecimal minimumPrice) {
		set("minimum_price", minimumPrice);
	}

	public java.math.BigDecimal getMinimumPrice() {
		return get("minimum_price");
	}

	public void setMinimumQuantity(Integer minimumQuantity) {
		set("minimum_quantity", minimumQuantity);
	}

	public Integer getMinimumQuantity() {
		return get("minimum_quantity");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setPoint(Long point) {
		set("point", point);
	}

	public Long getPoint() {
		return get("point");
	}

	public void setPrefix(String prefix) {
		set("prefix", prefix);
	}

	public String getPrefix() {
		return get("prefix");
	}

	public void setPriceExpression(String priceExpression) {
		set("price_expression", priceExpression);
	}

	public String getPriceExpression() {
		return get("price_expression");
	}

	public void setProductId(Long productId) {
		set("product_id", productId);
	}

	public Long getProductId() {
		return get("product_id");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setCount(Integer count) {
		set("count", count);
	}

	public Integer getCount() {
		return get("count");
	}

}
