package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActivity<M extends BaseActivity<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setOpporName(String opporName) {
		set("opporName", opporName);
	}

	public String getOpporName() {
		return get("opporName");
	}

	public void setGoodId(Long goodId) {
		set("good_id", goodId);
	}

	public Long getGoodId() {
		return get("good_id");
	}

	public void setGoodName(String goodName) {
		set("goodName", goodName);
	}

	public String getGoodName() {
		return get("goodName");
	}

	public void setNumber(Integer number) {
		set("number", number);
	}

	public Integer getNumber() {
		return get("number");
	}

	public void setPtNum(Integer ptNum) {
		set("ptNum", ptNum);
	}

	public Integer getPtNum() {
		return get("ptNum");
	}

	public void setBeginDate(java.util.Date beginDate) {
		set("beginDate", beginDate);
	}

	public java.util.Date getBeginDate() {
		return get("beginDate");
	}

	public void setEndDate(java.util.Date endDate) {
		set("endDate", endDate);
	}

	public java.util.Date getEndDate() {
		return get("endDate");
	}

	public void setForeNumber(Integer foreNumber) {
		set("foreNumber", foreNumber);
	}

	public Integer getForeNumber() {
		return get("foreNumber");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

	public void setNowNumber(Integer nowNumber) {
		set("nowNumber", nowNumber);
	}

	public Integer getNowNumber() {
		return get("nowNumber");
	}

	public void setOrderId(Long orderId) {
		set("order_id", orderId);
	}

	public Long getOrderId() {
		return get("order_id");
	}

	public void setStatus(String status) {
		set("status", status);
	}

	public String getStatus() {
		return get("status");
	}

	public void setOneMaxGoods(Integer oneMaxGoods) {
		set("oneMaxGoods", oneMaxGoods);
	}

	public Integer getOneMaxGoods() {
		return get("oneMaxGoods");
	}

	public void setLotteryExp(java.util.Date lotteryExp) {
		set("lotteryExp", lotteryExp);
	}

	public java.util.Date getLotteryExp() {
		return get("lotteryExp");
	}

	public void setPoint(java.math.BigDecimal point) {
		set("point", point);
	}

	public java.math.BigDecimal getPoint() {
		return get("point");
	}

	public void setLuckyNumber(Integer luckyNumber) {
		set("luckyNumber", luckyNumber);
	}

	public Integer getLuckyNumber() {
		return get("luckyNumber");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setRule(String rule) {
		set("rule", rule);
	}

	public String getRule() {
		return get("rule");
	}

	public void setExplain(String explain) {
		set("explain", explain);
	}

	public String getExplain() {
		return get("explain");
	}

}
