package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMiaobiLssuelog<M extends BaseMiaobiLssuelog<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setStatus(Boolean status) {
		set("status", status);
	}

	public Boolean getStatus() {
		return get("status");
	}

	public void setExplain(String explain) {
		set("explain", explain);
	}

	public String getExplain() {
		return get("explain");
	}

	public void setCount(Integer count) {
		set("count", count);
	}

	public Integer getCount() {
		return get("count");
	}

	public void setSales(Integer sales) {
		set("sales", sales);
	}

	public Integer getSales() {
		return get("sales");
	}

	public void setTeamnum(Integer teamnum) {
		set("teamnum", teamnum);
	}

	public Integer getTeamnum() {
		return get("teamnum");
	}

	public void setGroupnum(Integer groupnum) {
		set("groupnum", groupnum);
	}

	public Integer getGroupnum() {
		return get("groupnum");
	}

	public void setBeginDate(java.util.Date beginDate) {
		set("begin_date", beginDate);
	}

	public java.util.Date getBeginDate() {
		return get("begin_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setNumber(Integer number) {
		set("number", number);
	}

	public Integer getNumber() {
		return get("number");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

	public void setMiaobilId(Long miaobilId) {
		set("miaobil_id", miaobilId);
	}

	public Long getMiaobilId() {
		return get("miaobil_id");
	}

}
