package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommissionHistory<M extends BaseCommissionHistory<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setTyep(Integer tyep) {
		set("tyep", tyep);
	}

	public Integer getTyep() {
		return get("tyep");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

	public void setGoodsId(Long goodsId) {
		set("goods_id", goodsId);
	}

	public Long getGoodsId() {
		return get("goods_id");
	}

	public void setStaffId(Long staffId) {
		set("staff_id", staffId);
	}

	public Long getStaffId() {
		return get("staff_id");
	}

	public void setOrganId(String organId) {
		set("organ_id", organId);
	}

	public String getOrganId() {
		return get("organ_id");
	}

}
