package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGroupsJoin<M extends BaseGroupsJoin<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setMasterId(Integer masterId) {
		set("master_id", masterId);
	}

	public Integer getMasterId() {
		return get("master_id");
	}

	public void setUserId(Integer userId) {
		set("userId", userId);
	}

	public Integer getUserId() {
		return get("userId");
	}

	public void setSerialno(Integer serialno) {
		set("serialno", serialno);
	}

	public Integer getSerialno() {
		return get("serialno");
	}

}
