package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBargain<M extends BaseBargain<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setEndtime(Integer endtime) {
		set("endtime", endtime);
	}

	public Integer getEndtime() {
		return get("endtime");
	}

	public void setTitle(Integer title) {
		set("title", title);
	}

	public Integer getTitle() {
		return get("title");
	}

}
