package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTicketsn<M extends BaseTicketsn<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setSn(String sn) {
		set("sn", sn);
	}

	public String getSn() {
		return get("sn");
	}

	public void setOrderId(Long orderId) {
		set("orderId", orderId);
	}

	public Long getOrderId() {
		return get("orderId");
	}

	public void setConfigId(Long configId) {
		set("configId", configId);
	}

	public Long getConfigId() {
		return get("configId");
	}

	public void setMemberId(Long memberId) {
		set("memberId", memberId);
	}

	public Long getMemberId() {
		return get("memberId");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setMaxShareNum(Integer maxShareNum) {
		set("maxShareNum", maxShareNum);
	}

	public Integer getMaxShareNum() {
		return get("maxShareNum");
	}

	public void setCurrentNum(Integer currentNum) {
		set("currentNum", currentNum);
	}

	public Integer getCurrentNum() {
		return get("currentNum");
	}

}
