package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeamManagement<M extends BaseTeamManagement<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setAvatar(String avatar) {
		set("avatar", avatar);
	}

	public String getAvatar() {
		return get("avatar");
	}

	public void setShareCode(String shareCode) {
		set("share_code", shareCode);
	}

	public String getShareCode() {
		return get("share_code");
	}

	public void setMemeberNum(java.math.BigDecimal memeberNum) {
		set("memeber_num", memeberNum);
	}

	public java.math.BigDecimal getMemeberNum() {
		return get("memeber_num");
	}

	public void setOrderNum(java.math.BigDecimal orderNum) {
		set("order_num", orderNum);
	}

	public java.math.BigDecimal getOrderNum() {
		return get("order_num");
	}

	public void setPriceNum(java.math.BigDecimal priceNum) {
		set("price_num", priceNum);
	}

	public java.math.BigDecimal getPriceNum() {
		return get("price_num");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setWeChatNumber(String weChatNumber) {
		set("we_chat_number", weChatNumber);
	}

	public String getWeChatNumber() {
		return get("we_chat_number");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

	public void setNickname(String nickname) {
		set("nickname", nickname);
	}

	public String getNickname() {
		return get("nickname");
	}

	public void setHousername(String housername) {
		set("housername", housername);
	}

	public String getHousername() {
		return get("housername");
	}

}
