package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReverseAuctionHistroy<M extends BaseReverseAuctionHistroy<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setReverseAuctionId(Long reverseAuctionId) {
		set("reverse_auction_id", reverseAuctionId);
	}

	public Long getReverseAuctionId() {
		return get("reverse_auction_id");
	}

	public void setReverseAuctionDetailId(Long reverseAuctionDetailId) {
		set("reverse_auction_detail_id", reverseAuctionDetailId);
	}

	public Long getReverseAuctionDetailId() {
		return get("reverse_auction_detail_id");
	}

	public void setReversePruductId(Long reversePruductId) {
		set("reverse_pruduct_id", reversePruductId);
	}

	public Long getReversePruductId() {
		return get("reverse_pruduct_id");
	}

	public void setStartPrice(Double startPrice) {
		set("start_price", startPrice);
	}

	public Double getStartPrice() {
		return get("start_price");
	}

	public void setBuyNo(String buyNo) {
		set("buy_no", buyNo);
	}

	public String getBuyNo() {
		return get("buy_no");
	}

	public void setBuyState(Integer buyState) {
		set("buy_state", buyState);
	}

	public Integer getBuyState() {
		return get("buy_state");
	}

	public void setBuyPrice(Double buyPrice) {
		set("buy_price", buyPrice);
	}

	public Double getBuyPrice() {
		return get("buy_price");
	}

	public void setBuyTime(java.util.Date buyTime) {
		set("buy_time", buyTime);
	}

	public java.util.Date getBuyTime() {
		return get("buy_time");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

	public void setUserName(String userName) {
		set("user_name", userName);
	}

	public String getUserName() {
		return get("user_name");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

}
