package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return get("content");
	}

	public void setIp(String ip) {
		set("ip", ip);
	}

	public String getIp() {
		return get("ip");
	}

	public void setIsDraft(Boolean isDraft) {
		set("is_draft", isDraft);
	}

	public Boolean getIsDraft() {
		return get("is_draft");
	}

	public void setReceiverDelete(Boolean receiverDelete) {
		set("receiver_delete", receiverDelete);
	}

	public Boolean getReceiverDelete() {
		return get("receiver_delete");
	}

	public void setReceiverRead(Boolean receiverRead) {
		set("receiver_read", receiverRead);
	}

	public Boolean getReceiverRead() {
		return get("receiver_read");
	}

	public void setSenderDelete(Boolean senderDelete) {
		set("sender_delete", senderDelete);
	}

	public Boolean getSenderDelete() {
		return get("sender_delete");
	}

	public void setSenderRead(Boolean senderRead) {
		set("sender_read", senderRead);
	}

	public Boolean getSenderRead() {
		return get("sender_read");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setForMessageId(Long forMessageId) {
		set("for_message_id", forMessageId);
	}

	public Long getForMessageId() {
		return get("for_message_id");
	}

	public void setReceiverId(Long receiverId) {
		set("receiver_id", receiverId);
	}

	public Long getReceiverId() {
		return get("receiver_id");
	}

	public void setSenderId(Long senderId) {
		set("sender_id", senderId);
	}

	public Long getSenderId() {
		return get("sender_id");
	}

}
