package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdmin<M extends BaseAdmin<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setDepartment(String department) {
		set("department", department);
	}

	public String getDepartment() {
		return get("department");
	}

	public void setEmail(String email) {
		set("email", email);
	}

	public String getEmail() {
		return get("email");
	}

	public void setIsEnabled(Boolean isEnabled) {
		set("is_enabled", isEnabled);
	}

	public Boolean getIsEnabled() {
		return get("is_enabled");
	}

	public void setIsLocked(Boolean isLocked) {
		set("is_locked", isLocked);
	}

	public Boolean getIsLocked() {
		return get("is_locked");
	}

	public void setLockKey(String lockKey) {
		set("lock_key", lockKey);
	}

	public String getLockKey() {
		return get("lock_key");
	}

	public void setLockedDate(java.util.Date lockedDate) {
		set("locked_date", lockedDate);
	}

	public java.util.Date getLockedDate() {
		return get("locked_date");
	}

	public void setLoginDate(java.util.Date loginDate) {
		set("login_date", loginDate);
	}

	public java.util.Date getLoginDate() {
		return get("login_date");
	}

	public void setLoginFailureCount(Integer loginFailureCount) {
		set("login_failure_count", loginFailureCount);
	}

	public Integer getLoginFailureCount() {
		return get("login_failure_count");
	}

	public void setLoginIp(String loginIp) {
		set("login_ip", loginIp);
	}

	public String getLoginIp() {
		return get("login_ip");
	}

	public void setHasher(String hasher) {
		set("hasher", hasher);
	}

	public String getHasher() {
		return get("hasher");
	}

	public void setSalt(String salt) {
		set("salt", salt);
	}

	public String getSalt() {
		return get("salt");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setPassword(String password) {
		set("password", password);
	}

	public String getPassword() {
		return get("password");
	}

	public void setUsername(String username) {
		set("username", username);
	}

	public String getUsername() {
		return get("username");
	}

}
