package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGroupBuy<M extends BaseGroupBuy<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setOrders(Integer orders) {
		set("orders", orders);
	}

	public Integer getOrders() {
		return get("orders");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setPrice(Double price) {
		set("price", price);
	}

	public Double getPrice() {
		return get("price");
	}

	public void setUniprice(Double uniprice) {
		set("uniprice", uniprice);
	}

	public Double getUniprice() {
		return get("uniprice");
	}

	public void setNum(Integer num) {
		set("num", num);
	}

	public Integer getNum() {
		return get("num");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setRule(String rule) {
		set("rule", rule);
	}

	public String getRule() {
		return get("rule");
	}

	public void setProductImages(String productImages) {
		set("product_images", productImages);
	}

	public String getProductImages() {
		return get("product_images");
	}

	public void setImage(String image) {
		set("image", image);
	}

	public String getImage() {
		return get("image");
	}

	public void setQuestionImage(String questionImage) {
		set("questionImage", questionImage);
	}

	public String getQuestionImage() {
		return get("questionImage");
	}

	public void setExplain(String explain) {
		set("explain", explain);
	}

	public String getExplain() {
		return get("explain");
	}

	public void setProductId(Integer productId) {
		set("productId", productId);
	}

	public Integer getProductId() {
		return get("productId");
	}

	public void setCount(Integer count) {
		set("count", count);
	}

	public Integer getCount() {
		return get("count");
	}

	public void setSales(Integer sales) {
		set("sales", sales);
	}

	public Integer getSales() {
		return get("sales");
	}

	public void setTeamnum(Integer teamnum) {
		set("teamnum", teamnum);
	}

	public Integer getTeamnum() {
		return get("teamnum");
	}

	public void setDispatchprice(Double dispatchprice) {
		set("dispatchprice", dispatchprice);
	}

	public Double getDispatchprice() {
		return get("dispatchprice");
	}

	public void setGroupnum(Integer groupnum) {
		set("groupnum", groupnum);
	}

	public Integer getGroupnum() {
		return get("groupnum");
	}

	public void setEndtime(Integer endtime) {
		set("endtime", endtime);
	}

	public Integer getEndtime() {
		return get("endtime");
	}

	public void setIsMarketable(Boolean isMarketable) {
		set("is_marketable", isMarketable);
	}

	public Boolean getIsMarketable() {
		return get("is_marketable");
	}

	public void setIsList(Boolean isList) {
		set("is_list", isList);
	}

	public Boolean getIsList() {
		return get("is_list");
	}

	public void setIsTop(Boolean isTop) {
		set("is_top", isTop);
	}

	public Boolean getIsTop() {
		return get("is_top");
	}

	public void setIsSinglepurchase(Boolean isSinglepurchase) {
		set("is_singlepurchase", isSinglepurchase);
	}

	public Boolean getIsSinglepurchase() {
		return get("is_singlepurchase");
	}

}
