package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReceiver<M extends BaseReceiver<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setAddress(String address) {
		set("address", address);
	}

	public String getAddress() {
		return get("address");
	}

	public void setAreaName(String areaName) {
		set("area_name", areaName);
	}

	public String getAreaName() {
		return get("area_name");
	}

	public void setConsignee(String consignee) {
		set("consignee", consignee);
	}

	public String getConsignee() {
		return get("consignee");
	}

	public void setIsDefault(Boolean isDefault) {
		set("is_default", isDefault);
	}

	public Boolean getIsDefault() {
		return get("is_default");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

	public void setZipCode(String zipCode) {
		set("zip_code", zipCode);
	}

	public String getZipCode() {
		return get("zip_code");
	}

	public void setAreaId(Long areaId) {
		set("area_id", areaId);
	}

	public Long getAreaId() {
		return get("area_id");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

}
