package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseParameter<M extends BaseParameter<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setOrders(Integer orders) {
		set("orders", orders);
	}

	public Integer getOrders() {
		return get("orders");
	}

	public void setParameterGroup(String parameterGroup) {
		set("parameter_group", parameterGroup);
	}

	public String getParameterGroup() {
		return get("parameter_group");
	}

	public void setNames(String names) {
		set("names", names);
	}

	public String getNames() {
		return get("names");
	}

	public void setProductCategoryId(Long productCategoryId) {
		set("product_category_id", productCategoryId);
	}

	public Long getProductCategoryId() {
		return get("product_category_id");
	}

}
