package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticleTag<M extends BaseArticleTag<M>> extends Model<M> implements IBean {

	public void setArticles(Long articles) {
		set("articles", articles);
	}

	public Long getArticles() {
		return get("articles");
	}

	public void setTags(Long tags) {
		set("tags", tags);
	}

	public Long getTags() {
		return get("tags");
	}

}
