package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGroups<M extends BaseGroups<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setProductId(Integer productId) {
		set("product_id", productId);
	}

	public Integer getProductId() {
		return get("product_id");
	}

	public void setGroupPrice(Integer groupPrice) {
		set("group_price", groupPrice);
	}

	public Integer getGroupPrice() {
		return get("group_price");
	}

	public void setPublicNum(Integer publicNum) {
		set("public_num", publicNum);
	}

	public Integer getPublicNum() {
		return get("public_num");
	}

	public void setPrivateNum(Integer privateNum) {
		set("private_num", privateNum);
	}

	public Integer getPrivateNum() {
		return get("private_num");
	}

	public void setValidTime(Integer validTime) {
		set("valid_time", validTime);
	}

	public Integer getValidTime() {
		return get("valid_time");
	}

}
