package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsReviewComment<M extends BaseGoodsReviewComment<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setGoodsReviewId(Long goodsReviewId) {
		set("goods_review_id", goodsReviewId);
	}

	public Long getGoodsReviewId() {
		return get("goods_review_id");
	}

	public void setSummary(String summary) {
		set("summary", summary);
	}

	public String getSummary() {
		return get("summary");
	}

	public void setAdminId(Long adminId) {
		set("admin_id", adminId);
	}

	public Long getAdminId() {
		return get("admin_id");
	}

	public void setCommentDate(String commentDate) {
		set("comment_date", commentDate);
	}

	public String getCommentDate() {
		return get("comment_date");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setIsDelete(Integer isDelete) {
		set("is_delete", isDelete);
	}

	public Integer getIsDelete() {
		return get("is_delete");
	}

}
