package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShipping<M extends BaseShipping<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setAddress(String address) {
		set("address", address);
	}

	public String getAddress() {
		return get("address");
	}

	public void setArea(String area) {
		set("area", area);
	}

	public String getArea() {
		return get("area");
	}

	public void setConsignee(String consignee) {
		set("consignee", consignee);
	}

	public String getConsignee() {
		return get("consignee");
	}

	public void setDeliveryCorp(String deliveryCorp) {
		set("delivery_corp", deliveryCorp);
	}

	public String getDeliveryCorp() {
		return get("delivery_corp");
	}

	public void setDeliveryCorpCode(String deliveryCorpCode) {
		set("delivery_corp_code", deliveryCorpCode);
	}

	public String getDeliveryCorpCode() {
		return get("delivery_corp_code");
	}

	public void setDeliveryCorpUrl(String deliveryCorpUrl) {
		set("delivery_corp_url", deliveryCorpUrl);
	}

	public String getDeliveryCorpUrl() {
		return get("delivery_corp_url");
	}

	public void setFreight(java.math.BigDecimal freight) {
		set("freight", freight);
	}

	public java.math.BigDecimal getFreight() {
		return get("freight");
	}

	public void setMemo(String memo) {
		set("memo", memo);
	}

	public String getMemo() {
		return get("memo");
	}

	public void setOperator(String operator) {
		set("operator", operator);
	}

	public String getOperator() {
		return get("operator");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

	public void setShippingMethod(String shippingMethod) {
		set("shipping_method", shippingMethod);
	}

	public String getShippingMethod() {
		return get("shipping_method");
	}

	public void setSn(String sn) {
		set("sn", sn);
	}

	public String getSn() {
		return get("sn");
	}

	public void setTrackingNo(String trackingNo) {
		set("tracking_no", trackingNo);
	}

	public String getTrackingNo() {
		return get("tracking_no");
	}

	public void setZipCode(String zipCode) {
		set("zip_code", zipCode);
	}

	public String getZipCode() {
		return get("zip_code");
	}

	public void setOrderId(Long orderId) {
		set("order_id", orderId);
	}

	public Long getOrderId() {
		return get("order_id");
	}

}
