package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseButlerUpgradeLog<M extends BaseButlerUpgradeLog<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setMemo(String memo) {
		set("memo", memo);
	}

	public String getMemo() {
		return get("memo");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setMemberId(Long memberId) {
		set("member_id", memberId);
	}

	public Long getMemberId() {
		return get("member_id");
	}

	public void setUpDate(java.util.Date upDate) {
		set("up_date", upDate);
	}

	public java.util.Date getUpDate() {
		return get("up_date");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setIdcard(String idcard) {
		set("idcard", idcard);
	}

	public String getIdcard() {
		return get("idcard");
	}

	public void setImagez(String imagez) {
		set("imagez", imagez);
	}

	public String getImagez() {
		return get("imagez");
	}

	public void setImagef(String imagef) {
		set("imagef", imagef);
	}

	public String getImagef() {
		return get("imagef");
	}

	public void setSex(Boolean sex) {
		set("sex", sex);
	}

	public Boolean getSex() {
		return get("sex");
	}

	public void setAddress(String address) {
		set("address", address);
	}

	public String getAddress() {
		return get("address");
	}

	public void setBankName(String bankName) {
		set("bank_name", bankName);
	}

	public String getBankName() {
		return get("bank_name");
	}

	public void setBankCard(String bankCard) {
		set("bank_card", bankCard);
	}

	public String getBankCard() {
		return get("bank_card");
	}

	public void setBandz(String bandz) {
		set("bandz", bandz);
	}

	public String getBandz() {
		return get("bandz");
	}

	public void setBandf(String bandf) {
		set("bandf", bandf);
	}

	public String getBandf() {
		return get("bandf");
	}

	public void setBank(String bank) {
		set("bank", bank);
	}

	public String getBank() {
		return get("bank");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

}
