package com.wtshop.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePluginConfig<M extends BasePluginConfig<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setVersion(Long version) {
		set("version", version);
	}

	public Long getVersion() {
		return get("version");
	}

	public void setOrders(Integer orders) {
		set("orders", orders);
	}

	public Integer getOrders() {
		return get("orders");
	}

	public void setAttributes(String attributes) {
		set("attributes", attributes);
	}

	public String getAttributes() {
		return get("attributes");
	}

	public void setIsEnabled(Boolean isEnabled) {
		set("is_enabled", isEnabled);
	}

	public Boolean getIsEnabled() {
		return get("is_enabled");
	}

	public void setPluginId(String pluginId) {
		set("plugin_id", pluginId);
	}

	public String getPluginId() {
		return get("plugin_id");
	}

}
